language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "node"
install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
scripts:
  - npm run install:globals:all
  - npm run run install:all
  - npm run build:all:aot
  - npm run build:dev:jit
