/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '../../../../../src/app-components/nav/sidebar/nav-sidebar.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/debug_context';
import * as import3 from '@angular/core/src/render/api';
import * as import4 from '@angular/core/src/linker/element';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '../../../../../src/app-components/services/appstate.service';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '@angular/router/src/directives/router_link';
import * as import13 from '../../../../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import14 from '@angular/router/src/router';
import * as import15 from '@angular/router/src/router_state';
import * as import16 from '@angular/common/src/location/location_strategy';
export class Wrapper_NavSidebarComponent {
  context:import0.NavSidebarComponent;
  changed:boolean;
  constructor(p0:any) {
    this.changed = false;
    this.context = new import0.NavSidebarComponent(p0);
  }
  detectChangesInInputProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  detectChangesInHostProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
const nodeDebugInfos_NavSidebarComponent_Host0:import2.StaticNodeDebugInfo[] = [new import2.StaticNodeDebugInfo([import0.NavSidebarComponent],import0.NavSidebarComponent,{})];
var renderType_NavSidebarComponent_Host:import3.RenderComponentType = (null as any);
class _View_NavSidebarComponent_Host0 extends import1.DebugAppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import4.AppElement;
  _NavSidebarComponent_0_4:Wrapper_NavSidebarComponent;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_NavSidebarComponent_Host0,renderType_NavSidebarComponent_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_NavSidebarComponent_Host0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    this._el_0 = import5.selectOrCreateRenderHostElement(this.renderer,'nav-sidebar',import5.EMPTY_INLINE_ARRAY,rootSelector,this.debug(0,0,0));
    this._appEl_0 = new import4.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_NavSidebarComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._NavSidebarComponent_0_4 = new Wrapper_NavSidebarComponent(this.parentInjector.get(import9.AppState));
    this._appEl_0.initComponent(this._NavSidebarComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._NavSidebarComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.NavSidebarComponent) && (0 === requestNodeIndex))) { return this._NavSidebarComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(0,0,0);
    this._NavSidebarComponent_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._NavSidebarComponent_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_NavSidebarComponent_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import1.AppView<any> {
  if ((renderType_NavSidebarComponent_Host === (null as any))) { (renderType_NavSidebarComponent_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_NavSidebarComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const NavSidebarComponentNgFactory:import11.ComponentFactory<import0.NavSidebarComponent> = new import11.ComponentFactory<import0.NavSidebarComponent>('nav-sidebar',viewFactory_NavSidebarComponent_Host0,import0.NavSidebarComponent);
const styles_NavSidebarComponent:any[] = ([] as any[]);
const nodeDebugInfos_NavSidebarComponent0:import2.StaticNodeDebugInfo[] = [
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([import12.RouterLinkWithHref],(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([import12.RouterLinkWithHref],(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([import12.RouterLinkWithHref],(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([import12.RouterLinkWithHref],(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([import12.RouterLinkWithHref],(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([import12.RouterLinkWithHref],(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([import12.RouterLinkWithHref],(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([import12.RouterLinkWithHref],(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo([import12.RouterLinkWithHref],(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{}),
  new import2.StaticNodeDebugInfo(([] as any[]),(null as any),{})
]
;
var renderType_NavSidebarComponent:import3.RenderComponentType = (null as any);
class _View_NavSidebarComponent0 extends import1.DebugAppView<import0.NavSidebarComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _el_3:any;
  _RouterLinkWithHref_3_3:import13.Wrapper_RouterLinkWithHref;
  _text_4:any;
  _text_5:any;
  _el_6:any;
  _el_7:any;
  _RouterLinkWithHref_7_3:import13.Wrapper_RouterLinkWithHref;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _el_11:any;
  _RouterLinkWithHref_11_3:import13.Wrapper_RouterLinkWithHref;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _el_15:any;
  _RouterLinkWithHref_15_3:import13.Wrapper_RouterLinkWithHref;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _el_19:any;
  _RouterLinkWithHref_19_3:import13.Wrapper_RouterLinkWithHref;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _el_23:any;
  _RouterLinkWithHref_23_3:import13.Wrapper_RouterLinkWithHref;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _el_27:any;
  _RouterLinkWithHref_27_3:import13.Wrapper_RouterLinkWithHref;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _el_44:any;
  _el_45:any;
  _RouterLinkWithHref_45_3:import13.Wrapper_RouterLinkWithHref;
  _text_46:any;
  _text_47:any;
  _el_48:any;
  _el_49:any;
  _RouterLinkWithHref_49_3:import13.Wrapper_RouterLinkWithHref;
  _text_50:any;
  _text_51:any;
  _text_52:any;
  _text_53:any;
  _text_54:any;
  _text_55:any;
  _text_56:any;
  _text_57:any;
  _el_58:any;
  _el_59:any;
  _text_60:any;
  _text_61:any;
  _text_62:any;
  _text_63:any;
  _text_64:any;
  _text_65:any;
  _text_66:any;
  _text_67:any;
  _text_68:any;
  _text_69:any;
  _text_70:any;
  _text_71:any;
  _text_72:any;
  _text_73:any;
  _arr_83:any;
  _arr_84:any;
  _arr_85:any;
  _arr_86:any;
  _arr_87:any;
  _arr_88:any;
  _arr_89:any;
  _arr_90:any;
  _arr_91:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_NavSidebarComponent0,renderType_NavSidebarComponent,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_NavSidebarComponent0);
    this._arr_83 = import5.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._arr_84 = import5.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._arr_85 = import5.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._arr_86 = import5.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._arr_87 = import5.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._arr_88 = import5.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._arr_89 = import5.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._arr_90 = import5.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._arr_91 = import5.pureProxy1((p0:any):any[] => {
      return [p0];
    });
  }
  createInternal(rootSelector:string):import4.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = import5.createRenderElement(this.renderer,parentRenderNode,'ul',new import5.InlineArray4(4,'class','side-nav fixed','id','slide-out'),this.debug(0,0,0));
    this._text_1 = this.renderer.createText(this._el_0,'\n   ',this.debug(1,0,42));
    this._el_2 = import5.createRenderElement(this.renderer,this._el_0,'li',import5.EMPTY_INLINE_ARRAY,this.debug(2,1,3));
    this._el_3 = import5.createRenderElement(this.renderer,this._el_2,'a',new import5.InlineArray4(4,'class','waves-effect waves-darkblue','router-active',''),this.debug(3,1,7));
    this._RouterLinkWithHref_3_3 = new import13.Wrapper_RouterLinkWithHref(this.parentInjector.get(import14.Router),this.parentInjector.get(import15.ActivatedRoute),this.parentInjector.get(import16.LocationStrategy));
    this._text_4 = this.renderer.createText(this._el_3,'Index',this.debug(4,1,81));
    this._text_5 = this.renderer.createText(this._el_0,'\n   ',this.debug(5,1,95));
    this._el_6 = import5.createRenderElement(this.renderer,this._el_0,'li',import5.EMPTY_INLINE_ARRAY,this.debug(6,2,3));
    this._el_7 = import5.createRenderElement(this.renderer,this._el_6,'a',new import5.InlineArray4(4,'class','waves-effect waves-darkblue','router-active',''),this.debug(7,2,7));
    this._RouterLinkWithHref_7_3 = new import13.Wrapper_RouterLinkWithHref(this.parentInjector.get(import14.Router),this.parentInjector.get(import15.ActivatedRoute),this.parentInjector.get(import16.LocationStrategy));
    this._text_8 = this.renderer.createText(this._el_7,'Home',this.debug(8,2,85));
    this._text_9 = this.renderer.createText(this._el_0,'\n   ',this.debug(9,2,98));
    this._el_10 = import5.createRenderElement(this.renderer,this._el_0,'li',import5.EMPTY_INLINE_ARRAY,this.debug(10,3,3));
    this._el_11 = import5.createRenderElement(this.renderer,this._el_10,'a',new import5.InlineArray4(4,'class','waves-effect waves-darkblue','router-active',''),this.debug(11,3,7));
    this._RouterLinkWithHref_11_3 = new import13.Wrapper_RouterLinkWithHref(this.parentInjector.get(import14.Router),this.parentInjector.get(import15.ActivatedRoute),this.parentInjector.get(import16.LocationStrategy));
    this._text_12 = this.renderer.createText(this._el_11,'Ticket',this.debug(12,3,87));
    this._text_13 = this.renderer.createText(this._el_0,'\n   ',this.debug(13,3,102));
    this._el_14 = import5.createRenderElement(this.renderer,this._el_0,'li',import5.EMPTY_INLINE_ARRAY,this.debug(14,4,3));
    this._el_15 = import5.createRenderElement(this.renderer,this._el_14,'a',new import5.InlineArray4(4,'class','waves-effect waves-darkblue','router-active',''),this.debug(15,4,7));
    this._RouterLinkWithHref_15_3 = new import13.Wrapper_RouterLinkWithHref(this.parentInjector.get(import14.Router),this.parentInjector.get(import15.ActivatedRoute),this.parentInjector.get(import16.LocationStrategy));
    this._text_16 = this.renderer.createText(this._el_15,'Subscriber',this.debug(16,4,91));
    this._text_17 = this.renderer.createText(this._el_0,'\n   ',this.debug(17,4,110));
    this._el_18 = import5.createRenderElement(this.renderer,this._el_0,'li',import5.EMPTY_INLINE_ARRAY,this.debug(18,5,3));
    this._el_19 = import5.createRenderElement(this.renderer,this._el_18,'a',new import5.InlineArray4(4,'class','waves-effect waves-darkblue','router-active',''),this.debug(19,5,7));
    this._RouterLinkWithHref_19_3 = new import13.Wrapper_RouterLinkWithHref(this.parentInjector.get(import14.Router),this.parentInjector.get(import15.ActivatedRoute),this.parentInjector.get(import16.LocationStrategy));
    this._text_20 = this.renderer.createText(this._el_19,'About',this.debug(20,5,86));
    this._text_21 = this.renderer.createText(this._el_0,'\n   ',this.debug(21,5,100));
    this._el_22 = import5.createRenderElement(this.renderer,this._el_0,'li',import5.EMPTY_INLINE_ARRAY,this.debug(22,6,3));
    this._el_23 = import5.createRenderElement(this.renderer,this._el_22,'a',new import5.InlineArray4(4,'class','waves-effect waves-darkblue','router-active',''),this.debug(23,6,7));
    this._RouterLinkWithHref_23_3 = new import13.Wrapper_RouterLinkWithHref(this.parentInjector.get(import14.Router),this.parentInjector.get(import15.ActivatedRoute),this.parentInjector.get(import16.LocationStrategy));
    this._text_24 = this.renderer.createText(this._el_23,'Login',this.debug(24,6,86));
    this._text_25 = this.renderer.createText(this._el_0,'\n   ',this.debug(25,6,100));
    this._el_26 = import5.createRenderElement(this.renderer,this._el_0,'li',import5.EMPTY_INLINE_ARRAY,this.debug(26,7,3));
    this._el_27 = import5.createRenderElement(this.renderer,this._el_26,'a',new import5.InlineArray4(4,'class','waves-effect waves-darkblue','router-active',''),this.debug(27,7,7));
    this._RouterLinkWithHref_27_3 = new import13.Wrapper_RouterLinkWithHref(this.parentInjector.get(import14.Router),this.parentInjector.get(import15.ActivatedRoute),this.parentInjector.get(import16.LocationStrategy));
    this._text_28 = this.renderer.createText(this._el_27,'Detail (Sub Module)',this.debug(28,7,87));
    this._text_29 = this.renderer.createText(this._el_0,'\n\n   ',this.debug(29,7,115));
    this._el_30 = import5.createRenderElement(this.renderer,this._el_0,'li',new import5.InlineArray2(2,'class','no-padding'),this.debug(30,9,3));
    this._text_31 = this.renderer.createText(this._el_30,'\n      ',this.debug(31,9,26));
    this._el_32 = import5.createRenderElement(this.renderer,this._el_30,'ul',new import5.InlineArray4(4,'class','collapsible','data-collapsible','expandable'),this.debug(32,10,6));
    this._text_33 = this.renderer.createText(this._el_32,'\n         ',this.debug(33,10,60));
    this._el_34 = import5.createRenderElement(this.renderer,this._el_32,'li',import5.EMPTY_INLINE_ARRAY,this.debug(34,11,9));
    this._text_35 = this.renderer.createText(this._el_34,'\n            ',this.debug(35,11,13));
    this._el_36 = import5.createRenderElement(this.renderer,this._el_34,'a',new import5.InlineArray2(2,'class','collapsible-header'),this.debug(36,12,12));
    this._text_37 = this.renderer.createText(this._el_36,'Iframe Module',this.debug(37,12,78));
    this._el_38 = import5.createRenderElement(this.renderer,this._el_36,'i',new import5.InlineArray2(2,'class','mdi-navigation-arrow-drop-down'),this.debug(38,12,91));
    this._text_39 = this.renderer.createText(this._el_34,'\n            ',this.debug(39,12,141));
    this._el_40 = import5.createRenderElement(this.renderer,this._el_34,'div',new import5.InlineArray2(2,'class','collapsible-body'),this.debug(40,13,12));
    this._text_41 = this.renderer.createText(this._el_40,'\n               ',this.debug(41,13,42));
    this._el_42 = import5.createRenderElement(this.renderer,this._el_40,'ul',import5.EMPTY_INLINE_ARRAY,this.debug(42,14,15));
    this._text_43 = this.renderer.createText(this._el_42,'\n                  ',this.debug(43,14,19));
    this._el_44 = import5.createRenderElement(this.renderer,this._el_42,'li',import5.EMPTY_INLINE_ARRAY,this.debug(44,15,18));
    this._el_45 = import5.createRenderElement(this.renderer,this._el_44,'a',new import5.InlineArray4(4,'class','waves-effect waves-darkblue','router-active',''),this.debug(45,15,22));
    this._RouterLinkWithHref_45_3 = new import13.Wrapper_RouterLinkWithHref(this.parentInjector.get(import14.Router),this.parentInjector.get(import15.ActivatedRoute),this.parentInjector.get(import16.LocationStrategy));
    this._text_46 = this.renderer.createText(this._el_45,'Bing Images',this.debug(46,15,111));
    this._text_47 = this.renderer.createText(this._el_42,'\n                  ',this.debug(47,15,131));
    this._el_48 = import5.createRenderElement(this.renderer,this._el_42,'li',import5.EMPTY_INLINE_ARRAY,this.debug(48,16,18));
    this._el_49 = import5.createRenderElement(this.renderer,this._el_48,'a',new import5.InlineArray4(4,'class','waves-effect waves-darkblue','router-active',''),this.debug(49,16,22));
    this._RouterLinkWithHref_49_3 = new import13.Wrapper_RouterLinkWithHref(this.parentInjector.get(import14.Router),this.parentInjector.get(import15.ActivatedRoute),this.parentInjector.get(import16.LocationStrategy));
    this._text_50 = this.renderer.createText(this._el_49,'Bing Search',this.debug(50,16,111));
    this._text_51 = this.renderer.createText(this._el_42,'\n               ',this.debug(51,16,131));
    this._text_52 = this.renderer.createText(this._el_40,'\n            ',this.debug(52,17,20));
    this._text_53 = this.renderer.createText(this._el_34,'\n         ',this.debug(53,18,18));
    this._text_54 = this.renderer.createText(this._el_32,'\n      ',this.debug(54,19,14));
    this._text_55 = this.renderer.createText(this._el_30,'\n   ',this.debug(55,20,11));
    this._text_56 = this.renderer.createText(this._el_0,'\n',this.debug(56,21,8));
    this._text_57 = this.renderer.createText(parentRenderNode,'\n',this.debug(57,22,5));
    this._el_58 = import5.createRenderElement(this.renderer,parentRenderNode,'a',new import5.InlineArray8(6,'class','waves-effect waves-darkblue button-collapse','data-activates','slide-out','href','#'),this.debug(58,23,0));
    this._el_59 = import5.createRenderElement(this.renderer,this._el_58,'i',new import5.InlineArray2(2,'class','mdi-navigation-menu'),this.debug(59,23,91));
    this._text_60 = this.renderer.createText(parentRenderNode,'\n\n',this.debug(60,23,130));
    this._text_61 = this.renderer.createText(parentRenderNode,'\n',this.debug(61,25,23));
    this._text_62 = this.renderer.createText(parentRenderNode,'\n\n',this.debug(62,26,148));
    this._text_63 = this.renderer.createText(parentRenderNode,'\n',this.debug(63,28,74));
    this._text_64 = this.renderer.createText(parentRenderNode,'\n\n',this.debug(64,29,24));
    this._text_65 = this.renderer.createText(parentRenderNode,'\n',this.debug(65,31,23));
    this._text_66 = this.renderer.createText(parentRenderNode,'\n',this.debug(66,32,77));
    this._text_67 = this.renderer.createText(parentRenderNode,'\n\n',this.debug(67,33,24));
    this._text_68 = this.renderer.createText(parentRenderNode,'\n',this.debug(68,35,23));
    this._text_69 = this.renderer.createText(parentRenderNode,'\n',this.debug(69,36,79));
    this._text_70 = this.renderer.createText(parentRenderNode,'\n\n',this.debug(70,37,24));
    this._text_71 = this.renderer.createText(parentRenderNode,'\n',this.debug(71,39,23));
    this._text_72 = this.renderer.createText(parentRenderNode,'\n',this.debug(72,40,79));
    this._text_73 = this.renderer.createText(parentRenderNode,'\n\n',this.debug(73,41,24));
    var disposable_0:Function = this.renderer.listen(this._el_3,'click',this.eventHandler(this._handle_click_3_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_7,'click',this.eventHandler(this._handle_click_7_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_11,'click',this.eventHandler(this._handle_click_11_0.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_15,'click',this.eventHandler(this._handle_click_15_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_19,'click',this.eventHandler(this._handle_click_19_0.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_23,'click',this.eventHandler(this._handle_click_23_0.bind(this)));
    var disposable_6:Function = this.renderer.listen(this._el_27,'click',this.eventHandler(this._handle_click_27_0.bind(this)));
    var disposable_7:Function = this.renderer.listen(this._el_45,'click',this.eventHandler(this._handle_click_45_0.bind(this)));
    var disposable_8:Function = this.renderer.listen(this._el_49,'click',this.eventHandler(this._handle_click_49_0.bind(this)));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._el_3,
      this._text_4,
      this._text_5,
      this._el_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._el_44,
      this._el_45,
      this._text_46,
      this._text_47,
      this._el_48,
      this._el_49,
      this._text_50,
      this._text_51,
      this._text_52,
      this._text_53,
      this._text_54,
      this._text_55,
      this._text_56,
      this._text_57,
      this._el_58,
      this._el_59,
      this._text_60,
      this._text_61,
      this._text_62,
      this._text_63,
      this._text_64,
      this._text_65,
      this._text_66,
      this._text_67,
      this._text_68,
      this._text_69,
      this._text_70,
      this._text_71,
      this._text_72,
      this._text_73
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.RouterLinkWithHref) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._RouterLinkWithHref_3_3.context; }
    if (((token === import12.RouterLinkWithHref) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._RouterLinkWithHref_7_3.context; }
    if (((token === import12.RouterLinkWithHref) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._RouterLinkWithHref_11_3.context; }
    if (((token === import12.RouterLinkWithHref) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._RouterLinkWithHref_15_3.context; }
    if (((token === import12.RouterLinkWithHref) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._RouterLinkWithHref_19_3.context; }
    if (((token === import12.RouterLinkWithHref) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._RouterLinkWithHref_23_3.context; }
    if (((token === import12.RouterLinkWithHref) && ((27 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._RouterLinkWithHref_27_3.context; }
    if (((token === import12.RouterLinkWithHref) && ((45 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._RouterLinkWithHref_45_3.context; }
    if (((token === import12.RouterLinkWithHref) && ((49 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._RouterLinkWithHref_49_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(3,1,60);
    const currVal_3_0_0:any = this._arr_83('/');
    this._RouterLinkWithHref_3_3.check_routerLink(currVal_3_0_0,throwOnChange,false);
    this._RouterLinkWithHref_3_3.detectChangesInInputProps(this,this._el_3,throwOnChange);
    this.debug(7,2,60);
    const currVal_7_0_0:any = this._arr_84('/home');
    this._RouterLinkWithHref_7_3.check_routerLink(currVal_7_0_0,throwOnChange,false);
    this._RouterLinkWithHref_7_3.detectChangesInInputProps(this,this._el_7,throwOnChange);
    this.debug(11,3,60);
    const currVal_11_0_0:any = this._arr_85('/ticket');
    this._RouterLinkWithHref_11_3.check_routerLink(currVal_11_0_0,throwOnChange,false);
    this._RouterLinkWithHref_11_3.detectChangesInInputProps(this,this._el_11,throwOnChange);
    this.debug(15,4,60);
    const currVal_15_0_0:any = this._arr_86('/subscriber');
    this._RouterLinkWithHref_15_3.check_routerLink(currVal_15_0_0,throwOnChange,false);
    this._RouterLinkWithHref_15_3.detectChangesInInputProps(this,this._el_15,throwOnChange);
    this.debug(19,5,60);
    const currVal_19_0_0:any = this._arr_87('/about');
    this._RouterLinkWithHref_19_3.check_routerLink(currVal_19_0_0,throwOnChange,false);
    this._RouterLinkWithHref_19_3.detectChangesInInputProps(this,this._el_19,throwOnChange);
    this.debug(23,6,60);
    const currVal_23_0_0:any = this._arr_88('/login');
    this._RouterLinkWithHref_23_3.check_routerLink(currVal_23_0_0,throwOnChange,false);
    this._RouterLinkWithHref_23_3.detectChangesInInputProps(this,this._el_23,throwOnChange);
    this.debug(27,7,60);
    const currVal_27_0_0:any = this._arr_89('/detail');
    this._RouterLinkWithHref_27_3.check_routerLink(currVal_27_0_0,throwOnChange,false);
    this._RouterLinkWithHref_27_3.detectChangesInInputProps(this,this._el_27,throwOnChange);
    this.debug(45,15,75);
    const currVal_45_0_0:any = this._arr_90('/iframe/webpage1');
    this._RouterLinkWithHref_45_3.check_routerLink(currVal_45_0_0,throwOnChange,false);
    this._RouterLinkWithHref_45_3.detectChangesInInputProps(this,this._el_45,throwOnChange);
    this.debug(49,16,75);
    const currVal_49_0_0:any = this._arr_91('/iframe/webpage2');
    this._RouterLinkWithHref_49_3.check_routerLink(currVal_49_0_0,throwOnChange,false);
    this._RouterLinkWithHref_49_3.detectChangesInInputProps(this,this._el_49,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._RouterLinkWithHref_3_3.detectChangesInHostProps(this,this._el_3,throwOnChange);
    this._RouterLinkWithHref_7_3.detectChangesInHostProps(this,this._el_7,throwOnChange);
    this._RouterLinkWithHref_11_3.detectChangesInHostProps(this,this._el_11,throwOnChange);
    this._RouterLinkWithHref_15_3.detectChangesInHostProps(this,this._el_15,throwOnChange);
    this._RouterLinkWithHref_19_3.detectChangesInHostProps(this,this._el_19,throwOnChange);
    this._RouterLinkWithHref_23_3.detectChangesInHostProps(this,this._el_23,throwOnChange);
    this._RouterLinkWithHref_27_3.detectChangesInHostProps(this,this._el_27,throwOnChange);
    this._RouterLinkWithHref_45_3.detectChangesInHostProps(this,this._el_45,throwOnChange);
    this._RouterLinkWithHref_49_3.detectChangesInHostProps(this,this._el_49,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this.debug(3,1,7);
    this._RouterLinkWithHref_3_3.context.ngOnDestroy();
    this.debug(7,2,7);
    this._RouterLinkWithHref_7_3.context.ngOnDestroy();
    this.debug(11,3,7);
    this._RouterLinkWithHref_11_3.context.ngOnDestroy();
    this.debug(15,4,7);
    this._RouterLinkWithHref_15_3.context.ngOnDestroy();
    this.debug(19,5,7);
    this._RouterLinkWithHref_19_3.context.ngOnDestroy();
    this.debug(23,6,7);
    this._RouterLinkWithHref_23_3.context.ngOnDestroy();
    this.debug(27,7,7);
    this._RouterLinkWithHref_27_3.context.ngOnDestroy();
    this.debug(45,15,22);
    this._RouterLinkWithHref_45_3.context.ngOnDestroy();
    this.debug(49,16,22);
    this._RouterLinkWithHref_49_3.context.ngOnDestroy();
  }
  private _handle_click_3_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(3,1,7);
    const pd_3_0:any = ((<any>this._RouterLinkWithHref_3_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_3_0);
  }
  private _handle_click_7_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(7,2,7);
    const pd_7_0:any = ((<any>this._RouterLinkWithHref_7_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_7_0);
  }
  private _handle_click_11_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(11,3,7);
    const pd_11_0:any = ((<any>this._RouterLinkWithHref_11_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_11_0);
  }
  private _handle_click_15_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(15,4,7);
    const pd_15_0:any = ((<any>this._RouterLinkWithHref_15_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_15_0);
  }
  private _handle_click_19_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(19,5,7);
    const pd_19_0:any = ((<any>this._RouterLinkWithHref_19_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_19_0);
  }
  private _handle_click_23_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(23,6,7);
    const pd_23_0:any = ((<any>this._RouterLinkWithHref_23_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_23_0);
  }
  private _handle_click_27_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(27,7,7);
    const pd_27_0:any = ((<any>this._RouterLinkWithHref_27_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_27_0);
  }
  private _handle_click_45_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(45,15,22);
    const pd_45_0:any = ((<any>this._RouterLinkWithHref_45_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_45_0);
  }
  private _handle_click_49_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(49,16,22);
    const pd_49_0:any = ((<any>this._RouterLinkWithHref_49_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_49_0);
  }
}
export function viewFactory_NavSidebarComponent0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import1.AppView<import0.NavSidebarComponent> {
  if ((renderType_NavSidebarComponent === (null as any))) { (renderType_NavSidebarComponent = viewUtils.createRenderComponentType('C:/Source/GitHub/angular2-aot-webpack2-typescript-dotnet/master/src/app-components/nav/sidebar/nav-sidebar.template.html',0,import10.ViewEncapsulation.None,styles_NavSidebarComponent,{})); }
  return new _View_NavSidebarComponent0(viewUtils,parentInjector,declarationEl);
}