/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../../../src/app-components/app/app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/forms/src/directives';
import * as import6 from '@angular/forms/src/form_providers';
import * as import7 from '@angular/http/src/http_module';
import * as import8 from '@angular/router/src/router_module';
import * as import9 from '@angular2-material/core/ripple/ripple';
import * as import10 from '@angular2-material/button/button';
import * as import11 from '@angular2-material/card/card';
import * as import12 from '../../../../src/app-components/app/md.module';
import * as import13 from '@angular/core/src/application_init';
import * as import14 from '@angular/core/src/testability/testability';
import * as import15 from '@angular/core/src/application_ref';
import * as import16 from '../../../../src/app-components/services/appstate.service';
import * as import17 from '@angular/common/src/localization';
import * as import18 from '@angular/core/src/linker/compiler';
import * as import19 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import20 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import21 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import22 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import23 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import24 from '@angular/core/src/linker/view_utils';
import * as import25 from '@angular/platform-browser/src/browser/title';
import * as import26 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import27 from '@angular/http/src/backends/browser_xhr';
import * as import28 from '@angular/http/src/base_response_options';
import * as import29 from '@angular/http/src/backends/xhr_backend';
import * as import30 from '@angular/http/src/base_request_options';
import * as import31 from '@angular/common/src/location/location';
import * as import32 from '@angular/router/src/url_tree';
import * as import33 from '@angular/router/src/router_outlet_map';
import * as import34 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import35 from '@angular/router/src/router_preloader';
import * as import36 from '../../../../src/app-components/app/app.resolver';
import * as import37 from '../../../../src/app-components/services/utility.service';
import * as import38 from '../../../../src/app-components/services/authentication.service';
import * as import39 from '../../../../src/app-components/services/data.service';
import * as import40 from '../../../../src/app-components/services/route-protection.service';
import * as import41 from '@angular/core/src/di/injector';
import * as import42 from '../login/login.component.ngfactory';
import * as import43 from '../ticket/ticket.component.ngfactory';
import * as import44 from '../home/home.component.ngfactory';
import * as import45 from '../subscriber/subscriber.component.ngfactory';
import * as import46 from '../about/about.component.ngfactory';
import * as import47 from '../404/notfound404.component.ngfactory';
import * as import48 from './app.component.ngfactory';
import * as import49 from '@angular/core/src/application_tokens';
import * as import50 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import51 from '@angular/platform-browser/src/dom/events/key_events';
import * as import52 from '@angular/core/src/zone/ng_zone';
import * as import53 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import54 from '@angular/common/src/location/platform_location';
import * as import55 from '@angular/common/src/location/location_strategy';
import * as import56 from '../../../../src/app-components/login/login.component';
import * as import57 from '../../../../src/app-components/ticket/ticket.component';
import * as import58 from '../../../../src/app-components/home/home.component';
import * as import59 from '../../../../src/app-components/subscriber/subscriber.component';
import * as import60 from '../../../../src/app-components/about/about.component';
import * as import61 from '../../../../src/app-components/404/notfound404.component';
import * as import62 from '@angular/router/src/router';
import * as import63 from '@angular/core/src/console';
import * as import64 from '@angular/core/src/error_handler';
import * as import65 from '@angular/core/src/i18n/tokens';
import * as import66 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import67 from '@angular/platform-browser/src/dom/animation_driver';
import * as import68 from '@angular/core/src/render/api';
import * as import69 from '@angular/core/src/security';
import * as import70 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import71 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import72 from '@angular/http/src/interfaces';
import * as import73 from '@angular/http/src/http';
import * as import74 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import75 from '@angular/router/src/router_config_loader';
import * as import76 from '@angular/router/src/router_state';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _InternalFormsSharedModule_3:import5.InternalFormsSharedModule;
  _FormsModule_4:import6.FormsModule;
  _HttpModule_5:import7.HttpModule;
  _ROUTER_FORROOT_GUARD_6:any;
  _RouterModule_7:import8.RouterModule;
  _MdRippleModule_8:import9.MdRippleModule;
  _MdButtonModule_9:import10.MdButtonModule;
  _MdCardModule_10:import11.MdCardModule;
  _MdModule_11:import12.MdModule;
  _ErrorHandler_12:any;
  _ApplicationInitStatus_13:import13.ApplicationInitStatus;
  _Testability_14:import14.Testability;
  _ApplicationRef__15:import15.ApplicationRef_;
  _ApplicationRef_16:any;
  _AppState_17:import16.AppState;
  _AppModule_18:import1.AppModule;
  __LOCALE_ID_19:any;
  __NgLocalization_20:import17.NgLocaleLocalization;
  __Compiler_21:import18.Compiler;
  __APP_ID_22:any;
  __DOCUMENT_23:any;
  __HAMMER_GESTURE_CONFIG_24:import19.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_25:any[];
  __EventManager_26:import20.EventManager;
  __DomSharedStylesHost_27:import21.DomSharedStylesHost;
  __AnimationDriver_28:any;
  __DomRootRenderer_29:import22.DomRootRenderer_;
  __RootRenderer_30:any;
  __DomSanitizer_31:import23.DomSanitizerImpl;
  __Sanitizer_32:any;
  __ViewUtils_33:import24.ViewUtils;
  __IterableDiffers_34:any;
  __KeyValueDiffers_35:any;
  __SharedStylesHost_36:any;
  __Title_37:import25.Title;
  __RadioControlRegistry_38:import26.RadioControlRegistry;
  __BrowserXhr_39:import27.BrowserXhr;
  __ResponseOptions_40:import28.BaseResponseOptions;
  __XSRFStrategy_41:any;
  __XHRBackend_42:import29.XHRBackend;
  __RequestOptions_43:import30.BaseRequestOptions;
  __Http_44:any;
  __ROUTER_CONFIGURATION_45:any;
  __LocationStrategy_46:any;
  __Location_47:import31.Location;
  __UrlSerializer_48:import32.DefaultUrlSerializer;
  __RouterOutletMap_49:import33.RouterOutletMap;
  __NgModuleFactoryLoader_50:import34.SystemJsNgModuleLoader;
  __ROUTES_51:any[];
  __Router_52:any;
  __ActivatedRoute_53:any;
  _NoPreloading_54:import35.NoPreloading;
  _PreloadingStrategy_55:any;
  _RouterPreloader_56:import35.RouterPreloader;
  __PreloadAllModules_57:import35.PreloadAllModules;
  __APP_BOOTSTRAP_LISTENER_58:any[];
  __DataResolver_59:import36.DataResolver;
  __Logging_60:import37.Logging;
  __UtilityService_61:import37.UtilityService;
  __Authentication_62:import38.Authentication;
  __DataService_63:import39.DataService;
  __RouteProtection_64:import40.RouteProtection;
  constructor(parent:import41.Injector) {
    super(parent,[
      import42.LoginComponentNgFactory,
      import43.TicketComponentNgFactory,
      import43.TicketComponentNgFactory,
      import44.HomeComponentNgFactory,
      import44.HomeComponentNgFactory,
      import45.SubscriberComponentNgFactory,
      import42.LoginComponentNgFactory,
      import46.AboutComponentNgFactory,
      import47.NotFound404ComponentNgFactory,
      import47.NotFound404ComponentNgFactory,
      import48.AppComponentNgFactory
    ]
    ,[import48.AppComponentNgFactory]);
  }
  get _LOCALE_ID_19():any {
    if ((this.__LOCALE_ID_19 == (null as any))) { (this.__LOCALE_ID_19 = 'en-US'); }
    return this.__LOCALE_ID_19;
  }
  get _NgLocalization_20():import17.NgLocaleLocalization {
    if ((this.__NgLocalization_20 == (null as any))) { (this.__NgLocalization_20 = new import17.NgLocaleLocalization(this._LOCALE_ID_19)); }
    return this.__NgLocalization_20;
  }
  get _Compiler_21():import18.Compiler {
    if ((this.__Compiler_21 == (null as any))) { (this.__Compiler_21 = new import18.Compiler()); }
    return this.__Compiler_21;
  }
  get _APP_ID_22():any {
    if ((this.__APP_ID_22 == (null as any))) { (this.__APP_ID_22 = import49._appIdRandomProviderFactory()); }
    return this.__APP_ID_22;
  }
  get _DOCUMENT_23():any {
    if ((this.__DOCUMENT_23 == (null as any))) { (this.__DOCUMENT_23 = import4._document()); }
    return this.__DOCUMENT_23;
  }
  get _HAMMER_GESTURE_CONFIG_24():import19.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_24 == (null as any))) { (this.__HAMMER_GESTURE_CONFIG_24 = new import19.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_24;
  }
  get _EVENT_MANAGER_PLUGINS_25():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_25 == (null as any))) { (this.__EVENT_MANAGER_PLUGINS_25 = [
      new import50.DomEventsPlugin(),
      new import51.KeyEventsPlugin(),
      new import19.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_24)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_25;
  }
  get _EventManager_26():import20.EventManager {
    if ((this.__EventManager_26 == (null as any))) { (this.__EventManager_26 = new import20.EventManager(this._EVENT_MANAGER_PLUGINS_25,this.parent.get(import52.NgZone))); }
    return this.__EventManager_26;
  }
  get _DomSharedStylesHost_27():import21.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_27 == (null as any))) { (this.__DomSharedStylesHost_27 = new import21.DomSharedStylesHost(this._DOCUMENT_23)); }
    return this.__DomSharedStylesHost_27;
  }
  get _AnimationDriver_28():any {
    if ((this.__AnimationDriver_28 == (null as any))) { (this.__AnimationDriver_28 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_28;
  }
  get _DomRootRenderer_29():import22.DomRootRenderer_ {
    if ((this.__DomRootRenderer_29 == (null as any))) { (this.__DomRootRenderer_29 = new import22.DomRootRenderer_(this._DOCUMENT_23,this._EventManager_26,this._DomSharedStylesHost_27,this._AnimationDriver_28)); }
    return this.__DomRootRenderer_29;
  }
  get _RootRenderer_30():any {
    if ((this.__RootRenderer_30 == (null as any))) { (this.__RootRenderer_30 = import53._createConditionalRootRenderer(this._DomRootRenderer_29,this.parent.get(import53.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_30;
  }
  get _DomSanitizer_31():import23.DomSanitizerImpl {
    if ((this.__DomSanitizer_31 == (null as any))) { (this.__DomSanitizer_31 = new import23.DomSanitizerImpl()); }
    return this.__DomSanitizer_31;
  }
  get _Sanitizer_32():any {
    if ((this.__Sanitizer_32 == (null as any))) { (this.__Sanitizer_32 = this._DomSanitizer_31); }
    return this.__Sanitizer_32;
  }
  get _ViewUtils_33():import24.ViewUtils {
    if ((this.__ViewUtils_33 == (null as any))) { (this.__ViewUtils_33 = new import24.ViewUtils(this._RootRenderer_30,this._APP_ID_22,this._Sanitizer_32)); }
    return this.__ViewUtils_33;
  }
  get _IterableDiffers_34():any {
    if ((this.__IterableDiffers_34 == (null as any))) { (this.__IterableDiffers_34 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_34;
  }
  get _KeyValueDiffers_35():any {
    if ((this.__KeyValueDiffers_35 == (null as any))) { (this.__KeyValueDiffers_35 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_35;
  }
  get _SharedStylesHost_36():any {
    if ((this.__SharedStylesHost_36 == (null as any))) { (this.__SharedStylesHost_36 = this._DomSharedStylesHost_27); }
    return this.__SharedStylesHost_36;
  }
  get _Title_37():import25.Title {
    if ((this.__Title_37 == (null as any))) { (this.__Title_37 = new import25.Title()); }
    return this.__Title_37;
  }
  get _RadioControlRegistry_38():import26.RadioControlRegistry {
    if ((this.__RadioControlRegistry_38 == (null as any))) { (this.__RadioControlRegistry_38 = new import26.RadioControlRegistry()); }
    return this.__RadioControlRegistry_38;
  }
  get _BrowserXhr_39():import27.BrowserXhr {
    if ((this.__BrowserXhr_39 == (null as any))) { (this.__BrowserXhr_39 = new import27.BrowserXhr()); }
    return this.__BrowserXhr_39;
  }
  get _ResponseOptions_40():import28.BaseResponseOptions {
    if ((this.__ResponseOptions_40 == (null as any))) { (this.__ResponseOptions_40 = new import28.BaseResponseOptions()); }
    return this.__ResponseOptions_40;
  }
  get _XSRFStrategy_41():any {
    if ((this.__XSRFStrategy_41 == (null as any))) { (this.__XSRFStrategy_41 = import7._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_41;
  }
  get _XHRBackend_42():import29.XHRBackend {
    if ((this.__XHRBackend_42 == (null as any))) { (this.__XHRBackend_42 = new import29.XHRBackend(this._BrowserXhr_39,this._ResponseOptions_40,this._XSRFStrategy_41)); }
    return this.__XHRBackend_42;
  }
  get _RequestOptions_43():import30.BaseRequestOptions {
    if ((this.__RequestOptions_43 == (null as any))) { (this.__RequestOptions_43 = new import30.BaseRequestOptions()); }
    return this.__RequestOptions_43;
  }
  get _Http_44():any {
    if ((this.__Http_44 == (null as any))) { (this.__Http_44 = import7.httpFactory(this._XHRBackend_42,this._RequestOptions_43)); }
    return this.__Http_44;
  }
  get _ROUTER_CONFIGURATION_45():any {
    if ((this.__ROUTER_CONFIGURATION_45 == (null as any))) { (this.__ROUTER_CONFIGURATION_45 = {useHash: true}); }
    return this.__ROUTER_CONFIGURATION_45;
  }
  get _LocationStrategy_46():any {
    if ((this.__LocationStrategy_46 == (null as any))) { (this.__LocationStrategy_46 = import8.provideLocationStrategy(this.parent.get(import54.PlatformLocation),this.parent.get(import55.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_45)); }
    return this.__LocationStrategy_46;
  }
  get _Location_47():import31.Location {
    if ((this.__Location_47 == (null as any))) { (this.__Location_47 = new import31.Location(this._LocationStrategy_46)); }
    return this.__Location_47;
  }
  get _UrlSerializer_48():import32.DefaultUrlSerializer {
    if ((this.__UrlSerializer_48 == (null as any))) { (this.__UrlSerializer_48 = new import32.DefaultUrlSerializer()); }
    return this.__UrlSerializer_48;
  }
  get _RouterOutletMap_49():import33.RouterOutletMap {
    if ((this.__RouterOutletMap_49 == (null as any))) { (this.__RouterOutletMap_49 = new import33.RouterOutletMap()); }
    return this.__RouterOutletMap_49;
  }
  get _NgModuleFactoryLoader_50():import34.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_50 == (null as any))) { (this.__NgModuleFactoryLoader_50 = new import34.SystemJsNgModuleLoader(this._Compiler_21,this.parent.get(import34.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_50;
  }
  get _ROUTES_51():any[] {
      if ((this.__ROUTES_51 == (null as any))) { (this.__ROUTES_51 = [[
        {
          path: '',
          component: import56.LoginComponent
        }
        ,
        {
          path: 'detail',
          loadChildren: 'es6-promise?,[name]!../+detail/detail.module#DetailModule',
          canActivate: [import40.RouteProtection]
        }
        ,
        {
          path: 'iframe',
          loadChildren: 'es6-promise?,[name]!../+iframe-module/iframe.module#IframeModule',
          canActivate: [import40.RouteProtection]
        }
        ,
        {
          path: 'ticket',
          component: import57.TicketComponent,
          canActivate: [import40.RouteProtection]
        }
        ,
        {
          path: 'ticket/:ticketID',
          component: import57.TicketComponent,
          canActivate: [import40.RouteProtection]
        }
        ,
        {
          path: 'home',
          component: import58.HomeComponent,
          canActivate: [import40.RouteProtection]
        }
        ,
        {
          path: 'grid1',
          component: import58.HomeComponent,
          canActivate: [import40.RouteProtection]
        }
        ,
        {
          path: 'grid2',
          component: import59.SubscriberComponent,
          canActivate: [import40.RouteProtection]
        }
        ,
        {
          path: 'login',
          component: import56.LoginComponent
        }
        ,
        {
          path: 'about',
          component: import60.AboutComponent,
          canActivate: [import40.RouteProtection],
          resolve: {dataBroughtToComponent: import36.DataResolver}
        }
        ,
        {
          path: '**',
          component: import61.NotFound404Component
        }
        ,
        {
          path: '404',
          component: import61.NotFound404Component
        }

      ]
    ]); }
    return this.__ROUTES_51;
  }
  get _Router_52():any {
    if ((this.__Router_52 == (null as any))) { (this.__Router_52 = import8.setupRouter(this._ApplicationRef_16,this._UrlSerializer_48,this._RouterOutletMap_49,this._Location_47,this,this._NgModuleFactoryLoader_50,this._Compiler_21,this._ROUTES_51,this._ROUTER_CONFIGURATION_45)); }
    return this.__Router_52;
  }
  get _ActivatedRoute_53():any {
    if ((this.__ActivatedRoute_53 == (null as any))) { (this.__ActivatedRoute_53 = import8.rootRoute(this._Router_52)); }
    return this.__ActivatedRoute_53;
  }
  get _PreloadAllModules_57():import35.PreloadAllModules {
    if ((this.__PreloadAllModules_57 == (null as any))) { (this.__PreloadAllModules_57 = new import35.PreloadAllModules()); }
    return this.__PreloadAllModules_57;
  }
  get _APP_BOOTSTRAP_LISTENER_58():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_58 == (null as any))) { (this.__APP_BOOTSTRAP_LISTENER_58 = [import8.initialRouterNavigation(this._Router_52,this._ApplicationRef_16,this._RouterPreloader_56,this._ROUTER_CONFIGURATION_45)]); }
    return this.__APP_BOOTSTRAP_LISTENER_58;
  }
  get _DataResolver_59():import36.DataResolver {
    if ((this.__DataResolver_59 == (null as any))) { (this.__DataResolver_59 = new import36.DataResolver()); }
    return this.__DataResolver_59;
  }
  get _Logging_60():import37.Logging {
    if ((this.__Logging_60 == (null as any))) { (this.__Logging_60 = new import37.Logging()); }
    return this.__Logging_60;
  }
  get _UtilityService_61():import37.UtilityService {
    if ((this.__UtilityService_61 == (null as any))) { (this.__UtilityService_61 = new import37.UtilityService(this._Router_52)); }
    return this.__UtilityService_61;
  }
  get _Authentication_62():import38.Authentication {
    if ((this.__Authentication_62 == (null as any))) { (this.__Authentication_62 = new import38.Authentication(this._AppState_17,this._Router_52,this._Http_44,this._UtilityService_61)); }
    return this.__Authentication_62;
  }
  get _DataService_63():import39.DataService {
    if ((this.__DataService_63 == (null as any))) { (this.__DataService_63 = new import39.DataService(this._Http_44)); }
    return this.__DataService_63;
  }
  get _RouteProtection_64():import40.RouteProtection {
    if ((this.__RouteProtection_64 == (null as any))) { (this.__RouteProtection_64 = new import40.RouteProtection(this._AppState_17,this._UtilityService_61,this._Location_47,this._Authentication_62)); }
    return this.__RouteProtection_64;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._InternalFormsSharedModule_3 = new import5.InternalFormsSharedModule();
    this._FormsModule_4 = new import6.FormsModule();
    this._HttpModule_5 = new import7.HttpModule();
    this._ROUTER_FORROOT_GUARD_6 = import8.provideForRootGuard(this.parent.get(import62.Router,(null as any)));
    this._RouterModule_7 = new import8.RouterModule(this._ROUTER_FORROOT_GUARD_6);
    this._MdRippleModule_8 = new import9.MdRippleModule();
    this._MdButtonModule_9 = new import10.MdButtonModule();
    this._MdCardModule_10 = new import11.MdCardModule();
    this._MdModule_11 = new import12.MdModule();
    this._ErrorHandler_12 = import4.errorHandler();
    this._ApplicationInitStatus_13 = new import13.ApplicationInitStatus(this.parent.get(import13.APP_INITIALIZER,(null as any)));
    this._Testability_14 = new import14.Testability(this.parent.get(import52.NgZone));
    this._ApplicationRef__15 = new import15.ApplicationRef_(this.parent.get(import52.NgZone),this.parent.get(import63.Console),this,this._ErrorHandler_12,this,this._ApplicationInitStatus_13,this.parent.get(import14.TestabilityRegistry,(null as any)),this._Testability_14);
    this._ApplicationRef_16 = this._ApplicationRef__15;
    this._AppState_17 = new import16.AppState();
    this._AppModule_18 = new import1.AppModule(this._ApplicationRef_16,this._AppState_17);
    this._NoPreloading_54 = new import35.NoPreloading();
    this._PreloadingStrategy_55 = this._NoPreloading_54;
    this._RouterPreloader_56 = new import35.RouterPreloader(this._Router_52,this._NgModuleFactoryLoader_50,this._Compiler_21,this,this._PreloadingStrategy_55);
    return this._AppModule_18;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_3; }
    if ((token === import6.FormsModule)) { return this._FormsModule_4; }
    if ((token === import7.HttpModule)) { return this._HttpModule_5; }
    if ((token === import8.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_6; }
    if ((token === import8.RouterModule)) { return this._RouterModule_7; }
    if ((token === import9.MdRippleModule)) { return this._MdRippleModule_8; }
    if ((token === import10.MdButtonModule)) { return this._MdButtonModule_9; }
    if ((token === import11.MdCardModule)) { return this._MdCardModule_10; }
    if ((token === import12.MdModule)) { return this._MdModule_11; }
    if ((token === import64.ErrorHandler)) { return this._ErrorHandler_12; }
    if ((token === import13.ApplicationInitStatus)) { return this._ApplicationInitStatus_13; }
    if ((token === import14.Testability)) { return this._Testability_14; }
    if ((token === import15.ApplicationRef_)) { return this._ApplicationRef__15; }
    if ((token === import15.ApplicationRef)) { return this._ApplicationRef_16; }
    if ((token === import16.AppState)) { return this._AppState_17; }
    if ((token === import1.AppModule)) { return this._AppModule_18; }
    if ((token === import65.LOCALE_ID)) { return this._LOCALE_ID_19; }
    if ((token === import17.NgLocalization)) { return this._NgLocalization_20; }
    if ((token === import18.Compiler)) { return this._Compiler_21; }
    if ((token === import49.APP_ID)) { return this._APP_ID_22; }
    if ((token === import66.DOCUMENT)) { return this._DOCUMENT_23; }
    if ((token === import19.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_24; }
    if ((token === import20.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_25; }
    if ((token === import20.EventManager)) { return this._EventManager_26; }
    if ((token === import21.DomSharedStylesHost)) { return this._DomSharedStylesHost_27; }
    if ((token === import67.AnimationDriver)) { return this._AnimationDriver_28; }
    if ((token === import22.DomRootRenderer)) { return this._DomRootRenderer_29; }
    if ((token === import68.RootRenderer)) { return this._RootRenderer_30; }
    if ((token === import23.DomSanitizer)) { return this._DomSanitizer_31; }
    if ((token === import69.Sanitizer)) { return this._Sanitizer_32; }
    if ((token === import24.ViewUtils)) { return this._ViewUtils_33; }
    if ((token === import70.IterableDiffers)) { return this._IterableDiffers_34; }
    if ((token === import71.KeyValueDiffers)) { return this._KeyValueDiffers_35; }
    if ((token === import21.SharedStylesHost)) { return this._SharedStylesHost_36; }
    if ((token === import25.Title)) { return this._Title_37; }
    if ((token === import26.RadioControlRegistry)) { return this._RadioControlRegistry_38; }
    if ((token === import27.BrowserXhr)) { return this._BrowserXhr_39; }
    if ((token === import28.ResponseOptions)) { return this._ResponseOptions_40; }
    if ((token === import72.XSRFStrategy)) { return this._XSRFStrategy_41; }
    if ((token === import29.XHRBackend)) { return this._XHRBackend_42; }
    if ((token === import30.RequestOptions)) { return this._RequestOptions_43; }
    if ((token === import73.Http)) { return this._Http_44; }
    if ((token === import8.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_45; }
    if ((token === import55.LocationStrategy)) { return this._LocationStrategy_46; }
    if ((token === import31.Location)) { return this._Location_47; }
    if ((token === import32.UrlSerializer)) { return this._UrlSerializer_48; }
    if ((token === import33.RouterOutletMap)) { return this._RouterOutletMap_49; }
    if ((token === import74.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_50; }
    if ((token === import75.ROUTES)) { return this._ROUTES_51; }
    if ((token === import62.Router)) { return this._Router_52; }
    if ((token === import76.ActivatedRoute)) { return this._ActivatedRoute_53; }
    if ((token === import35.NoPreloading)) { return this._NoPreloading_54; }
    if ((token === import35.PreloadingStrategy)) { return this._PreloadingStrategy_55; }
    if ((token === import35.RouterPreloader)) { return this._RouterPreloader_56; }
    if ((token === import35.PreloadAllModules)) { return this._PreloadAllModules_57; }
    if ((token === import49.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_58; }
    if ((token === import36.DataResolver)) { return this._DataResolver_59; }
    if ((token === import37.Logging)) { return this._Logging_60; }
    if ((token === import37.UtilityService)) { return this._UtilityService_61; }
    if ((token === import38.Authentication)) { return this._Authentication_62; }
    if ((token === import39.DataService)) { return this._DataService_63; }
    if ((token === import40.RouteProtection)) { return this._RouteProtection_64; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__15.ngOnDestroy();
    this._RouterPreloader_56.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);