/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../../../src/app-components/app/app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/forms/src/directives';
import * as import6 from '@angular/forms/src/form_providers';
import * as import7 from '@angular/http/src/http_module';
import * as import8 from '@angular/router/src/router_module';
import * as import9 from '@angular/core/src/application_init';
import * as import10 from '@angular/core/src/testability/testability';
import * as import11 from '@angular/core/src/application_ref';
import * as import12 from '../../../../src/app-components/services/appstate.service';
import * as import13 from '@angular/common/src/localization';
import * as import14 from '@angular/core/src/linker/compiler';
import * as import15 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import16 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import17 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import18 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import19 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import20 from '@angular/core/src/linker/view_utils';
import * as import21 from '@angular/platform-browser/src/browser/title';
import * as import22 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import23 from '@angular/http/src/backends/browser_xhr';
import * as import24 from '@angular/http/src/base_response_options';
import * as import25 from '@angular/http/src/backends/xhr_backend';
import * as import26 from '@angular/http/src/base_request_options';
import * as import27 from '@angular/common/src/location/location';
import * as import28 from '@angular/router/src/url_tree';
import * as import29 from '@angular/router/src/router_outlet_map';
import * as import30 from '@angular/core/src/linker/system_js_ng_module_factory_loader';
import * as import31 from '@angular/router/src/router_preloader';
import * as import32 from '../../../../src/app-components/app/app.resolver';
import * as import33 from '../../../../src/app-components/services/utility.service';
import * as import34 from '../../../../src/app-components/services/authentication.service';
import * as import35 from '../../../../src/app-components/services/data.service';
import * as import36 from '../../../../src/app-components/services/route-protection.service';
import * as import37 from '@angular/core/src/di/injector';
import * as import38 from '../login/login.component.ngfactory';
import * as import39 from '../ticket/ticket.component.ngfactory';
import * as import40 from '../home/home.component.ngfactory';
import * as import41 from '../subscriber/subscriber.component.ngfactory';
import * as import42 from '../about/about.component.ngfactory';
import * as import43 from '../404/notfound404.component.ngfactory';
import * as import44 from './app.component.ngfactory';
import * as import45 from '@angular/core/src/application_tokens';
import * as import46 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import47 from '@angular/platform-browser/src/dom/events/key_events';
import * as import48 from '@angular/core/src/zone/ng_zone';
import * as import49 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import50 from '@angular/common/src/location/platform_location';
import * as import51 from '@angular/common/src/location/location_strategy';
import * as import52 from '../../../../src/app-components/login/login.component';
import * as import53 from '../../../../src/app-components/ticket/ticket.component';
import * as import54 from '../../../../src/app-components/home/home.component';
import * as import55 from '../../../../src/app-components/subscriber/subscriber.component';
import * as import56 from '../../../../src/app-components/about/about.component';
import * as import57 from '../../../../src/app-components/404/notfound404.component';
import * as import58 from '@angular/router/src/router';
import * as import59 from '@angular/core/src/console';
import * as import60 from '@angular/core/src/error_handler';
import * as import61 from '@angular/core/src/i18n/tokens';
import * as import62 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import63 from '@angular/platform-browser/src/dom/animation_driver';
import * as import64 from '@angular/core/src/render/api';
import * as import65 from '@angular/core/src/security';
import * as import66 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import67 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import68 from '@angular/http/src/interfaces';
import * as import69 from '@angular/http/src/http';
import * as import70 from '@angular/core/src/linker/ng_module_factory_loader';
import * as import71 from '@angular/router/src/router_config_loader';
import * as import72 from '@angular/router/src/router_state';
import * as import73 from 'angular2-jwt/angular2-jwt';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _InternalFormsSharedModule_3:import5.InternalFormsSharedModule;
  _FormsModule_4:import6.FormsModule;
  _HttpModule_5:import7.HttpModule;
  _ROUTER_FORROOT_GUARD_6:any;
  _RouterModule_7:import8.RouterModule;
  _ErrorHandler_8:any;
  _ApplicationInitStatus_9:import9.ApplicationInitStatus;
  _Testability_10:import10.Testability;
  _ApplicationRef__11:import11.ApplicationRef_;
  _ApplicationRef_12:any;
  _AppState_13:import12.AppState;
  _AppModule_14:import1.AppModule;
  __LOCALE_ID_15:any;
  __NgLocalization_16:import13.NgLocaleLocalization;
  __Compiler_17:import14.Compiler;
  __APP_ID_18:any;
  __DOCUMENT_19:any;
  __HAMMER_GESTURE_CONFIG_20:import15.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_21:any[];
  __EventManager_22:import16.EventManager;
  __DomSharedStylesHost_23:import17.DomSharedStylesHost;
  __AnimationDriver_24:any;
  __DomRootRenderer_25:import18.DomRootRenderer_;
  __RootRenderer_26:any;
  __DomSanitizer_27:import19.DomSanitizerImpl;
  __Sanitizer_28:any;
  __ViewUtils_29:import20.ViewUtils;
  __IterableDiffers_30:any;
  __KeyValueDiffers_31:any;
  __SharedStylesHost_32:any;
  __Title_33:import21.Title;
  __RadioControlRegistry_34:import22.RadioControlRegistry;
  __BrowserXhr_35:import23.BrowserXhr;
  __ResponseOptions_36:import24.BaseResponseOptions;
  __XSRFStrategy_37:any;
  __XHRBackend_38:import25.XHRBackend;
  __RequestOptions_39:import26.BaseRequestOptions;
  __Http_40:any;
  __ROUTER_CONFIGURATION_41:any;
  __LocationStrategy_42:any;
  __Location_43:import27.Location;
  __UrlSerializer_44:import28.DefaultUrlSerializer;
  __RouterOutletMap_45:import29.RouterOutletMap;
  __NgModuleFactoryLoader_46:import30.SystemJsNgModuleLoader;
  __ROUTES_47:any[];
  __Router_48:any;
  __ActivatedRoute_49:any;
  _NoPreloading_50:import31.NoPreloading;
  _PreloadingStrategy_51:any;
  _RouterPreloader_52:import31.RouterPreloader;
  __PreloadAllModules_53:import31.PreloadAllModules;
  __APP_BOOTSTRAP_LISTENER_54:any[];
  __DataResolver_55:import32.DataResolver;
  __Logging_56:import33.Logging;
  __UtilityService_57:import33.UtilityService;
  __Authentication_58:import34.Authentication;
  __DataService_59:import35.DataService;
  __RouteProtection_60:import36.RouteProtection;
  __AuthHttp_61:any;
  constructor(parent:import37.Injector) {
    super(parent,[
      import38.LoginComponentNgFactory,
      import39.TicketComponentNgFactory,
      import39.TicketComponentNgFactory,
      import40.HomeComponentNgFactory,
      import41.SubscriberComponentNgFactory,
      import38.LoginComponentNgFactory,
      import42.AboutComponentNgFactory,
      import43.NotFound404ComponentNgFactory,
      import43.NotFound404ComponentNgFactory,
      import44.AppComponentNgFactory
    ]
    ,[import44.AppComponentNgFactory]);
  }
  get _LOCALE_ID_15():any {
    if ((this.__LOCALE_ID_15 == (null as any))) { (this.__LOCALE_ID_15 = 'en-US'); }
    return this.__LOCALE_ID_15;
  }
  get _NgLocalization_16():import13.NgLocaleLocalization {
    if ((this.__NgLocalization_16 == (null as any))) { (this.__NgLocalization_16 = new import13.NgLocaleLocalization(this._LOCALE_ID_15)); }
    return this.__NgLocalization_16;
  }
  get _Compiler_17():import14.Compiler {
    if ((this.__Compiler_17 == (null as any))) { (this.__Compiler_17 = new import14.Compiler()); }
    return this.__Compiler_17;
  }
  get _APP_ID_18():any {
    if ((this.__APP_ID_18 == (null as any))) { (this.__APP_ID_18 = import45._appIdRandomProviderFactory()); }
    return this.__APP_ID_18;
  }
  get _DOCUMENT_19():any {
    if ((this.__DOCUMENT_19 == (null as any))) { (this.__DOCUMENT_19 = import4._document()); }
    return this.__DOCUMENT_19;
  }
  get _HAMMER_GESTURE_CONFIG_20():import15.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_20 == (null as any))) { (this.__HAMMER_GESTURE_CONFIG_20 = new import15.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_20;
  }
  get _EVENT_MANAGER_PLUGINS_21():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_21 == (null as any))) { (this.__EVENT_MANAGER_PLUGINS_21 = [
      new import46.DomEventsPlugin(),
      new import47.KeyEventsPlugin(),
      new import15.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_20)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_21;
  }
  get _EventManager_22():import16.EventManager {
    if ((this.__EventManager_22 == (null as any))) { (this.__EventManager_22 = new import16.EventManager(this._EVENT_MANAGER_PLUGINS_21,this.parent.get(import48.NgZone))); }
    return this.__EventManager_22;
  }
  get _DomSharedStylesHost_23():import17.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_23 == (null as any))) { (this.__DomSharedStylesHost_23 = new import17.DomSharedStylesHost(this._DOCUMENT_19)); }
    return this.__DomSharedStylesHost_23;
  }
  get _AnimationDriver_24():any {
    if ((this.__AnimationDriver_24 == (null as any))) { (this.__AnimationDriver_24 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_24;
  }
  get _DomRootRenderer_25():import18.DomRootRenderer_ {
    if ((this.__DomRootRenderer_25 == (null as any))) { (this.__DomRootRenderer_25 = new import18.DomRootRenderer_(this._DOCUMENT_19,this._EventManager_22,this._DomSharedStylesHost_23,this._AnimationDriver_24)); }
    return this.__DomRootRenderer_25;
  }
  get _RootRenderer_26():any {
    if ((this.__RootRenderer_26 == (null as any))) { (this.__RootRenderer_26 = import49._createConditionalRootRenderer(this._DomRootRenderer_25,this.parent.get(import49.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_26;
  }
  get _DomSanitizer_27():import19.DomSanitizerImpl {
    if ((this.__DomSanitizer_27 == (null as any))) { (this.__DomSanitizer_27 = new import19.DomSanitizerImpl()); }
    return this.__DomSanitizer_27;
  }
  get _Sanitizer_28():any {
    if ((this.__Sanitizer_28 == (null as any))) { (this.__Sanitizer_28 = this._DomSanitizer_27); }
    return this.__Sanitizer_28;
  }
  get _ViewUtils_29():import20.ViewUtils {
    if ((this.__ViewUtils_29 == (null as any))) { (this.__ViewUtils_29 = new import20.ViewUtils(this._RootRenderer_26,this._APP_ID_18,this._Sanitizer_28)); }
    return this.__ViewUtils_29;
  }
  get _IterableDiffers_30():any {
    if ((this.__IterableDiffers_30 == (null as any))) { (this.__IterableDiffers_30 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_30;
  }
  get _KeyValueDiffers_31():any {
    if ((this.__KeyValueDiffers_31 == (null as any))) { (this.__KeyValueDiffers_31 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_31;
  }
  get _SharedStylesHost_32():any {
    if ((this.__SharedStylesHost_32 == (null as any))) { (this.__SharedStylesHost_32 = this._DomSharedStylesHost_23); }
    return this.__SharedStylesHost_32;
  }
  get _Title_33():import21.Title {
    if ((this.__Title_33 == (null as any))) { (this.__Title_33 = new import21.Title()); }
    return this.__Title_33;
  }
  get _RadioControlRegistry_34():import22.RadioControlRegistry {
    if ((this.__RadioControlRegistry_34 == (null as any))) { (this.__RadioControlRegistry_34 = new import22.RadioControlRegistry()); }
    return this.__RadioControlRegistry_34;
  }
  get _BrowserXhr_35():import23.BrowserXhr {
    if ((this.__BrowserXhr_35 == (null as any))) { (this.__BrowserXhr_35 = new import23.BrowserXhr()); }
    return this.__BrowserXhr_35;
  }
  get _ResponseOptions_36():import24.BaseResponseOptions {
    if ((this.__ResponseOptions_36 == (null as any))) { (this.__ResponseOptions_36 = new import24.BaseResponseOptions()); }
    return this.__ResponseOptions_36;
  }
  get _XSRFStrategy_37():any {
    if ((this.__XSRFStrategy_37 == (null as any))) { (this.__XSRFStrategy_37 = import7._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_37;
  }
  get _XHRBackend_38():import25.XHRBackend {
    if ((this.__XHRBackend_38 == (null as any))) { (this.__XHRBackend_38 = new import25.XHRBackend(this._BrowserXhr_35,this._ResponseOptions_36,this._XSRFStrategy_37)); }
    return this.__XHRBackend_38;
  }
  get _RequestOptions_39():import26.BaseRequestOptions {
    if ((this.__RequestOptions_39 == (null as any))) { (this.__RequestOptions_39 = new import26.BaseRequestOptions()); }
    return this.__RequestOptions_39;
  }
  get _Http_40():any {
    if ((this.__Http_40 == (null as any))) { (this.__Http_40 = import7.httpFactory(this._XHRBackend_38,this._RequestOptions_39)); }
    return this.__Http_40;
  }
  get _ROUTER_CONFIGURATION_41():any {
    if ((this.__ROUTER_CONFIGURATION_41 == (null as any))) { (this.__ROUTER_CONFIGURATION_41 = {useHash: true}); }
    return this.__ROUTER_CONFIGURATION_41;
  }
  get _LocationStrategy_42():any {
    if ((this.__LocationStrategy_42 == (null as any))) { (this.__LocationStrategy_42 = import8.provideLocationStrategy(this.parent.get(import50.PlatformLocation),this.parent.get(import51.APP_BASE_HREF,(null as any)),this._ROUTER_CONFIGURATION_41)); }
    return this.__LocationStrategy_42;
  }
  get _Location_43():import27.Location {
    if ((this.__Location_43 == (null as any))) { (this.__Location_43 = new import27.Location(this._LocationStrategy_42)); }
    return this.__Location_43;
  }
  get _UrlSerializer_44():import28.DefaultUrlSerializer {
    if ((this.__UrlSerializer_44 == (null as any))) { (this.__UrlSerializer_44 = new import28.DefaultUrlSerializer()); }
    return this.__UrlSerializer_44;
  }
  get _RouterOutletMap_45():import29.RouterOutletMap {
    if ((this.__RouterOutletMap_45 == (null as any))) { (this.__RouterOutletMap_45 = new import29.RouterOutletMap()); }
    return this.__RouterOutletMap_45;
  }
  get _NgModuleFactoryLoader_46():import30.SystemJsNgModuleLoader {
    if ((this.__NgModuleFactoryLoader_46 == (null as any))) { (this.__NgModuleFactoryLoader_46 = new import30.SystemJsNgModuleLoader(this._Compiler_17,this.parent.get(import30.SystemJsNgModuleLoaderConfig,(null as any)))); }
    return this.__NgModuleFactoryLoader_46;
  }
  get _ROUTES_47():any[] {
      if ((this.__ROUTES_47 == (null as any))) { (this.__ROUTES_47 = [[
        {
          path: '',
          component: import52.LoginComponent
        }
        ,
        {
          path: 'detail',
          loadChildren: 'es6-promise?,[name]!../+detail/detail.module#DetailModule',
          canActivate: [import36.RouteProtection]
        }
        ,
        {
          path: 'iframe',
          loadChildren: 'es6-promise?,[name]!../+iframe-module/iframe.module#IframeModule',
          canActivate: [import36.RouteProtection]
        }
        ,
        {
          path: 'ticket',
          component: import53.TicketComponent,
          canActivate: [import36.RouteProtection]
        }
        ,
        {
          path: 'ticket/:ticketID',
          component: import53.TicketComponent,
          canActivate: [import36.RouteProtection]
        }
        ,
        {
          path: 'home',
          component: import54.HomeComponent,
          canActivate: [import36.RouteProtection]
        }
        ,
        {
          path: 'subscriber',
          component: import55.SubscriberComponent,
          canActivate: [import36.RouteProtection]
        }
        ,
        {
          path: 'login',
          component: import52.LoginComponent
        }
        ,
        {
          path: 'about',
          component: import56.AboutComponent,
          canActivate: [import36.RouteProtection],
          resolve: {dataBroughtToComponent: import32.DataResolver}
        }
        ,
        {
          path: '**',
          component: import57.NotFound404Component
        }
        ,
        {
          path: '404',
          component: import57.NotFound404Component
        }

      ]
    ]); }
    return this.__ROUTES_47;
  }
  get _Router_48():any {
    if ((this.__Router_48 == (null as any))) { (this.__Router_48 = import8.setupRouter(this._ApplicationRef_12,this._UrlSerializer_44,this._RouterOutletMap_45,this._Location_43,this,this._NgModuleFactoryLoader_46,this._Compiler_17,this._ROUTES_47,this._ROUTER_CONFIGURATION_41)); }
    return this.__Router_48;
  }
  get _ActivatedRoute_49():any {
    if ((this.__ActivatedRoute_49 == (null as any))) { (this.__ActivatedRoute_49 = import8.rootRoute(this._Router_48)); }
    return this.__ActivatedRoute_49;
  }
  get _PreloadAllModules_53():import31.PreloadAllModules {
    if ((this.__PreloadAllModules_53 == (null as any))) { (this.__PreloadAllModules_53 = new import31.PreloadAllModules()); }
    return this.__PreloadAllModules_53;
  }
  get _APP_BOOTSTRAP_LISTENER_54():any[] {
    if ((this.__APP_BOOTSTRAP_LISTENER_54 == (null as any))) { (this.__APP_BOOTSTRAP_LISTENER_54 = [import8.initialRouterNavigation(this._Router_48,this._ApplicationRef_12,this._RouterPreloader_52,this._ROUTER_CONFIGURATION_41)]); }
    return this.__APP_BOOTSTRAP_LISTENER_54;
  }
  get _DataResolver_55():import32.DataResolver {
    if ((this.__DataResolver_55 == (null as any))) { (this.__DataResolver_55 = new import32.DataResolver()); }
    return this.__DataResolver_55;
  }
  get _Logging_56():import33.Logging {
    if ((this.__Logging_56 == (null as any))) { (this.__Logging_56 = new import33.Logging()); }
    return this.__Logging_56;
  }
  get _UtilityService_57():import33.UtilityService {
    if ((this.__UtilityService_57 == (null as any))) { (this.__UtilityService_57 = new import33.UtilityService(this._Router_48)); }
    return this.__UtilityService_57;
  }
  get _Authentication_58():import34.Authentication {
    if ((this.__Authentication_58 == (null as any))) { (this.__Authentication_58 = new import34.Authentication(this._AppState_13,this._Router_48,this._Http_40,this._UtilityService_57)); }
    return this.__Authentication_58;
  }
  get _DataService_59():import35.DataService {
    if ((this.__DataService_59 == (null as any))) { (this.__DataService_59 = new import35.DataService(this._Http_40)); }
    return this.__DataService_59;
  }
  get _RouteProtection_60():import36.RouteProtection {
    if ((this.__RouteProtection_60 == (null as any))) { (this.__RouteProtection_60 = new import36.RouteProtection(this._AppState_13,this._UtilityService_57,this._Location_43,this._Authentication_58)); }
    return this.__RouteProtection_60;
  }
  get _AuthHttp_61():any {
    if ((this.__AuthHttp_61 == (null as any))) { (this.__AuthHttp_61 = import1.authFactory(this._Http_40,this._RequestOptions_39)); }
    return this.__AuthHttp_61;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._InternalFormsSharedModule_3 = new import5.InternalFormsSharedModule();
    this._FormsModule_4 = new import6.FormsModule();
    this._HttpModule_5 = new import7.HttpModule();
    this._ROUTER_FORROOT_GUARD_6 = import8.provideForRootGuard(this.parent.get(import58.Router,(null as any)));
    this._RouterModule_7 = new import8.RouterModule(this._ROUTER_FORROOT_GUARD_6);
    this._ErrorHandler_8 = import4.errorHandler();
    this._ApplicationInitStatus_9 = new import9.ApplicationInitStatus(this.parent.get(import9.APP_INITIALIZER,(null as any)));
    this._Testability_10 = new import10.Testability(this.parent.get(import48.NgZone));
    this._ApplicationRef__11 = new import11.ApplicationRef_(this.parent.get(import48.NgZone),this.parent.get(import59.Console),this,this._ErrorHandler_8,this,this._ApplicationInitStatus_9,this.parent.get(import10.TestabilityRegistry,(null as any)),this._Testability_10);
    this._ApplicationRef_12 = this._ApplicationRef__11;
    this._AppState_13 = new import12.AppState();
    this._AppModule_14 = new import1.AppModule(this._ApplicationRef_12,this._AppState_13);
    this._NoPreloading_50 = new import31.NoPreloading();
    this._PreloadingStrategy_51 = this._NoPreloading_50;
    this._RouterPreloader_52 = new import31.RouterPreloader(this._Router_48,this._NgModuleFactoryLoader_46,this._Compiler_17,this,this._PreloadingStrategy_51);
    return this._AppModule_14;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_3; }
    if ((token === import6.FormsModule)) { return this._FormsModule_4; }
    if ((token === import7.HttpModule)) { return this._HttpModule_5; }
    if ((token === import8.ROUTER_FORROOT_GUARD)) { return this._ROUTER_FORROOT_GUARD_6; }
    if ((token === import8.RouterModule)) { return this._RouterModule_7; }
    if ((token === import60.ErrorHandler)) { return this._ErrorHandler_8; }
    if ((token === import9.ApplicationInitStatus)) { return this._ApplicationInitStatus_9; }
    if ((token === import10.Testability)) { return this._Testability_10; }
    if ((token === import11.ApplicationRef_)) { return this._ApplicationRef__11; }
    if ((token === import11.ApplicationRef)) { return this._ApplicationRef_12; }
    if ((token === import12.AppState)) { return this._AppState_13; }
    if ((token === import1.AppModule)) { return this._AppModule_14; }
    if ((token === import61.LOCALE_ID)) { return this._LOCALE_ID_15; }
    if ((token === import13.NgLocalization)) { return this._NgLocalization_16; }
    if ((token === import14.Compiler)) { return this._Compiler_17; }
    if ((token === import45.APP_ID)) { return this._APP_ID_18; }
    if ((token === import62.DOCUMENT)) { return this._DOCUMENT_19; }
    if ((token === import15.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_20; }
    if ((token === import16.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_21; }
    if ((token === import16.EventManager)) { return this._EventManager_22; }
    if ((token === import17.DomSharedStylesHost)) { return this._DomSharedStylesHost_23; }
    if ((token === import63.AnimationDriver)) { return this._AnimationDriver_24; }
    if ((token === import18.DomRootRenderer)) { return this._DomRootRenderer_25; }
    if ((token === import64.RootRenderer)) { return this._RootRenderer_26; }
    if ((token === import19.DomSanitizer)) { return this._DomSanitizer_27; }
    if ((token === import65.Sanitizer)) { return this._Sanitizer_28; }
    if ((token === import20.ViewUtils)) { return this._ViewUtils_29; }
    if ((token === import66.IterableDiffers)) { return this._IterableDiffers_30; }
    if ((token === import67.KeyValueDiffers)) { return this._KeyValueDiffers_31; }
    if ((token === import17.SharedStylesHost)) { return this._SharedStylesHost_32; }
    if ((token === import21.Title)) { return this._Title_33; }
    if ((token === import22.RadioControlRegistry)) { return this._RadioControlRegistry_34; }
    if ((token === import23.BrowserXhr)) { return this._BrowserXhr_35; }
    if ((token === import24.ResponseOptions)) { return this._ResponseOptions_36; }
    if ((token === import68.XSRFStrategy)) { return this._XSRFStrategy_37; }
    if ((token === import25.XHRBackend)) { return this._XHRBackend_38; }
    if ((token === import26.RequestOptions)) { return this._RequestOptions_39; }
    if ((token === import69.Http)) { return this._Http_40; }
    if ((token === import8.ROUTER_CONFIGURATION)) { return this._ROUTER_CONFIGURATION_41; }
    if ((token === import51.LocationStrategy)) { return this._LocationStrategy_42; }
    if ((token === import27.Location)) { return this._Location_43; }
    if ((token === import28.UrlSerializer)) { return this._UrlSerializer_44; }
    if ((token === import29.RouterOutletMap)) { return this._RouterOutletMap_45; }
    if ((token === import70.NgModuleFactoryLoader)) { return this._NgModuleFactoryLoader_46; }
    if ((token === import71.ROUTES)) { return this._ROUTES_47; }
    if ((token === import58.Router)) { return this._Router_48; }
    if ((token === import72.ActivatedRoute)) { return this._ActivatedRoute_49; }
    if ((token === import31.NoPreloading)) { return this._NoPreloading_50; }
    if ((token === import31.PreloadingStrategy)) { return this._PreloadingStrategy_51; }
    if ((token === import31.RouterPreloader)) { return this._RouterPreloader_52; }
    if ((token === import31.PreloadAllModules)) { return this._PreloadAllModules_53; }
    if ((token === import45.APP_BOOTSTRAP_LISTENER)) { return this._APP_BOOTSTRAP_LISTENER_54; }
    if ((token === import32.DataResolver)) { return this._DataResolver_55; }
    if ((token === import33.Logging)) { return this._Logging_56; }
    if ((token === import33.UtilityService)) { return this._UtilityService_57; }
    if ((token === import34.Authentication)) { return this._Authentication_58; }
    if ((token === import35.DataService)) { return this._DataService_59; }
    if ((token === import36.RouteProtection)) { return this._RouteProtection_60; }
    if ((token === import73.AuthHttp)) { return this._AuthHttp_61; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__11.ngOnDestroy();
    this._RouterPreloader_52.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);