/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/debug_context';
import * as import1 from '../../../../../src/app-components/nav/footer/nav-footer.component';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view';
import * as import4 from '@angular/core/src/linker/element';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '../../../../../src/app-components/services/appstate.service';
import * as import10 from '../../../../../src/app-components/services/authentication.service';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from '@angular/core/src/linker/template_ref';
import * as import14 from '@angular/common/src/directives/ng_if';
const nodeDebugInfos_NavFooterComponent_Host0:import0.StaticNodeDebugInfo[] = [new import0.StaticNodeDebugInfo([import1.NavFooterComponent],import1.NavFooterComponent,{})];
var renderType_NavFooterComponent_Host:import2.RenderComponentType = (null as any);
class _View_NavFooterComponent_Host0 extends import3.DebugAppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import4.AppElement;
  _NavFooterComponent_0_4:import1.NavFooterComponent;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_NavFooterComponent_Host0,renderType_NavFooterComponent_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_NavFooterComponent_Host0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    this._el_0 = this.selectOrCreateHostElement('nav-footer',rootSelector,this.debug(0,0,0));
    this._appEl_0 = new import4.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_NavFooterComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._NavFooterComponent_0_4 = new import1.NavFooterComponent(this.parentInjector.get(import9.AppState),this.parentInjector.get(import10.Authentication));
    this._appEl_0.initComponent(this._NavFooterComponent_0_4,[],compView_0);
    compView_0.create(this._NavFooterComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.NavFooterComponent) && (0 === requestNodeIndex))) { return this._NavFooterComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._NavFooterComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_NavFooterComponent_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<any> {
  if ((renderType_NavFooterComponent_Host === (null as any))) { (renderType_NavFooterComponent_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,[],{})); }
  return new _View_NavFooterComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const NavFooterComponentNgFactory:import12.ComponentFactory<import1.NavFooterComponent> = new import12.ComponentFactory<import1.NavFooterComponent>('nav-footer',viewFactory_NavFooterComponent_Host0,import1.NavFooterComponent);
const styles_NavFooterComponent:any[] = [];
const nodeDebugInfos_NavFooterComponent0:import0.StaticNodeDebugInfo[] = [
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([
    import13.TemplateRef,
    import14.NgIf
  ]
  ,(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{})
]
;
var renderType_NavFooterComponent:import2.RenderComponentType = (null as any);
class _View_NavFooterComponent0 extends import3.DebugAppView<import1.NavFooterComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _text_5:any;
  _anchor_6:any;
  /*private*/ _appEl_6:import4.AppElement;
  _TemplateRef_6_5:any;
  _NgIf_6_6:import14.NgIf;
  _text_7:any;
  _text_8:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_NavFooterComponent0,renderType_NavFooterComponent,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_NavFooterComponent0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',this.debug(0,0,48));
    this._el_1 = this.renderer.createElement(parentRenderNode,'div',this.debug(1,1,0));
    this.renderer.setElementAttribute(this._el_1,'class','text-align-center');
    this._text_2 = this.renderer.createText(this._el_1,'\n   ',this.debug(2,1,31));
    this._el_3 = this.renderer.createElement(this._el_1,'p',this.debug(3,2,3));
    this.renderer.setElementAttribute(this._el_3,'class','copyright');
    this._text_4 = this.renderer.createText(this._el_3,'Copyright © 2016 Helios. All rights reserved.',this.debug(4,2,24));
    this._text_5 = this.renderer.createText(this._el_1,'\n   ',this.debug(5,2,78));
    this._anchor_6 = this.renderer.createTemplateAnchor(this._el_1,this.debug(6,3,3));
    this._appEl_6 = new import4.AppElement(6,1,this,this._anchor_6);
    this._TemplateRef_6_5 = new import13.TemplateRef_(this._appEl_6,viewFactory_NavFooterComponent1);
    this._NgIf_6_6 = new import14.NgIf(this._appEl_6.vcRef,this._TemplateRef_6_5);
    this._text_7 = this.renderer.createText(this._el_1,'\n',this.debug(7,4,11));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n',this.debug(8,5,6));
    this._expr_0 = import8.UNINITIALIZED;
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._text_5,
      this._anchor_6,
      this._text_7,
      this._text_8
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.TemplateRef) && (6 === requestNodeIndex))) { return this._TemplateRef_6_5; }
    if (((token === import14.NgIf) && (6 === requestNodeIndex))) { return this._NgIf_6_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.debug(6,3,6);
    const currVal_0:any = this.context.appState.state.isAuthenticated;
    if (import5.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this._NgIf_6_6.ngIf = currVal_0;
      this._expr_0 = currVal_0;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_NavFooterComponent0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<import1.NavFooterComponent> {
  if ((renderType_NavFooterComponent === (null as any))) { (renderType_NavFooterComponent = viewUtils.createRenderComponentType('C:/Source/Atlas/src/app-components/nav/footer/nav-footer.template.html',0,import11.ViewEncapsulation.None,styles_NavFooterComponent,{})); }
  return new _View_NavFooterComponent0(viewUtils,parentInjector,declarationEl);
}
const nodeDebugInfos_NavFooterComponent1:import0.StaticNodeDebugInfo[] = [
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{})
]
;
class _View_NavFooterComponent1 extends import3.DebugAppView<any> {
  _el_0:any;
  _el_1:any;
  _text_2:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_NavFooterComponent1,renderType_NavFooterComponent,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_NavFooterComponent1);
  }
  createInternal(rootSelector:string):import4.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'p',this.debug(0,3,3));
    this._el_1 = this.renderer.createElement(this._el_0,'a',this.debug(1,3,45));
    this.renderer.setElementAttribute(this._el_1,'class','btn btn-primary btn-lg');
    this.renderer.setElementAttribute(this._el_1,'role','button');
    this._text_2 = this.renderer.createText(this._el_1,'Logout\n   ',this.debug(2,3,112));
    var disposable_0:Function = this.renderer.listen(this._el_1,'click',this.eventHandler(this._handle_click_1_0.bind(this)));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._el_1,
      this._text_2
    ]
    ,[disposable_0],[]);
    return (null as any);
  }
  private _handle_click_1_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(1,3,93);
    const pd_0:any = ((<any>this.parent.context.logout()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_NavFooterComponent1(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<any> {
  return new _View_NavFooterComponent1(viewUtils,parentInjector,declarationEl);
}