/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/debug_context';
import * as import1 from '../../../../../src/app-components/nav/sidebar/nav-sidebar.component';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/view';
import * as import4 from '@angular/core/src/linker/element';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '../../../../../src/app-components/services/appstate.service';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '@angular/router/src/directives/router_link';
import * as import13 from '@angular/router/src/router';
import * as import14 from '@angular/router/src/router_state';
import * as import15 from '@angular/common/src/location/location_strategy';
import * as import16 from '@angular/core/src/security';
const nodeDebugInfos_NavSidebarComponent_Host0:import0.StaticNodeDebugInfo[] = [new import0.StaticNodeDebugInfo([import1.NavSidebarComponent],import1.NavSidebarComponent,{})];
var renderType_NavSidebarComponent_Host:import2.RenderComponentType = (null as any);
class _View_NavSidebarComponent_Host0 extends import3.DebugAppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import4.AppElement;
  _NavSidebarComponent_0_4:import1.NavSidebarComponent;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_NavSidebarComponent_Host0,renderType_NavSidebarComponent_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_NavSidebarComponent_Host0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    this._el_0 = this.selectOrCreateHostElement('nav-sidebar',rootSelector,this.debug(0,0,0));
    this._appEl_0 = new import4.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_NavSidebarComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._NavSidebarComponent_0_4 = new import1.NavSidebarComponent(this.parentInjector.get(import9.AppState));
    this._appEl_0.initComponent(this._NavSidebarComponent_0_4,[],compView_0);
    compView_0.create(this._NavSidebarComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import1.NavSidebarComponent) && (0 === requestNodeIndex))) { return this._NavSidebarComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._NavSidebarComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_NavSidebarComponent_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<any> {
  if ((renderType_NavSidebarComponent_Host === (null as any))) { (renderType_NavSidebarComponent_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,[],{})); }
  return new _View_NavSidebarComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const NavSidebarComponentNgFactory:import11.ComponentFactory<import1.NavSidebarComponent> = new import11.ComponentFactory<import1.NavSidebarComponent>('nav-sidebar',viewFactory_NavSidebarComponent_Host0,import1.NavSidebarComponent);
const styles_NavSidebarComponent:any[] = [];
const nodeDebugInfos_NavSidebarComponent0:import0.StaticNodeDebugInfo[] = [
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([import12.RouterLinkWithHref],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([import12.RouterLinkWithHref],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([import12.RouterLinkWithHref],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([import12.RouterLinkWithHref],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([import12.RouterLinkWithHref],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([import12.RouterLinkWithHref],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([import12.RouterLinkWithHref],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([import12.RouterLinkWithHref],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([import12.RouterLinkWithHref],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{}),
  new import0.StaticNodeDebugInfo([],(null as any),{})
]
;
var renderType_NavSidebarComponent:import2.RenderComponentType = (null as any);
class _View_NavSidebarComponent0 extends import3.DebugAppView<import1.NavSidebarComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _el_3:any;
  _RouterLinkWithHref_3_3:import12.RouterLinkWithHref;
  _text_4:any;
  _text_5:any;
  _el_6:any;
  _el_7:any;
  _RouterLinkWithHref_7_3:import12.RouterLinkWithHref;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _el_11:any;
  _RouterLinkWithHref_11_3:import12.RouterLinkWithHref;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _el_15:any;
  _RouterLinkWithHref_15_3:import12.RouterLinkWithHref;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _el_19:any;
  _RouterLinkWithHref_19_3:import12.RouterLinkWithHref;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _el_23:any;
  _RouterLinkWithHref_23_3:import12.RouterLinkWithHref;
  _text_24:any;
  _text_25:any;
  _el_26:any;
  _el_27:any;
  _RouterLinkWithHref_27_3:import12.RouterLinkWithHref;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _el_44:any;
  _el_45:any;
  _RouterLinkWithHref_45_3:import12.RouterLinkWithHref;
  _text_46:any;
  _text_47:any;
  _el_48:any;
  _el_49:any;
  _RouterLinkWithHref_49_3:import12.RouterLinkWithHref;
  _text_50:any;
  _text_51:any;
  _text_52:any;
  _text_53:any;
  _text_54:any;
  _text_55:any;
  _text_56:any;
  _text_57:any;
  _el_58:any;
  _el_59:any;
  _text_60:any;
  _text_61:any;
  _text_62:any;
  _text_63:any;
  _text_64:any;
  _text_65:any;
  _text_66:any;
  _text_67:any;
  _text_68:any;
  _text_69:any;
  _text_70:any;
  _text_71:any;
  _text_72:any;
  _text_73:any;
  _arr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  _arr_1:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  _arr_2:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  _arr_3:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  _arr_4:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  _arr_5:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  _arr_6:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  _arr_7:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  _arr_8:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement) {
    super(_View_NavSidebarComponent0,renderType_NavSidebarComponent,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways,nodeDebugInfos_NavSidebarComponent0);
  }
  createInternal(rootSelector:string):import4.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ul',this.debug(0,0,0));
    this.renderer.setElementAttribute(this._el_0,'class','side-nav fixed');
    this.renderer.setElementAttribute(this._el_0,'id','slide-out');
    this._text_1 = this.renderer.createText(this._el_0,'\n   ',this.debug(1,0,42));
    this._el_2 = this.renderer.createElement(this._el_0,'li',this.debug(2,1,3));
    this._el_3 = this.renderer.createElement(this._el_2,'a',this.debug(3,1,7));
    this.renderer.setElementAttribute(this._el_3,'class','waves-effect waves-darkblue');
    this.renderer.setElementAttribute(this._el_3,'router-active','');
    this._RouterLinkWithHref_3_3 = new import12.RouterLinkWithHref(this.parentInjector.get(import13.Router),this.parentInjector.get(import14.ActivatedRoute),this.parentInjector.get(import15.LocationStrategy));
    this._text_4 = this.renderer.createText(this._el_3,'Index',this.debug(4,1,81));
    this._text_5 = this.renderer.createText(this._el_0,'\n   ',this.debug(5,1,95));
    this._el_6 = this.renderer.createElement(this._el_0,'li',this.debug(6,2,3));
    this._el_7 = this.renderer.createElement(this._el_6,'a',this.debug(7,2,7));
    this.renderer.setElementAttribute(this._el_7,'class','waves-effect waves-darkblue');
    this.renderer.setElementAttribute(this._el_7,'router-active','');
    this._RouterLinkWithHref_7_3 = new import12.RouterLinkWithHref(this.parentInjector.get(import13.Router),this.parentInjector.get(import14.ActivatedRoute),this.parentInjector.get(import15.LocationStrategy));
    this._text_8 = this.renderer.createText(this._el_7,'Ticket',this.debug(8,2,87));
    this._text_9 = this.renderer.createText(this._el_0,'\n   ',this.debug(9,2,102));
    this._el_10 = this.renderer.createElement(this._el_0,'li',this.debug(10,3,3));
    this._el_11 = this.renderer.createElement(this._el_10,'a',this.debug(11,3,7));
    this.renderer.setElementAttribute(this._el_11,'class','waves-effect waves-darkblue');
    this.renderer.setElementAttribute(this._el_11,'router-active','');
    this._RouterLinkWithHref_11_3 = new import12.RouterLinkWithHref(this.parentInjector.get(import13.Router),this.parentInjector.get(import14.ActivatedRoute),this.parentInjector.get(import15.LocationStrategy));
    this._text_12 = this.renderer.createText(this._el_11,'Grid (Editing)',this.debug(12,3,86));
    this._text_13 = this.renderer.createText(this._el_0,'\n   ',this.debug(13,3,109));
    this._el_14 = this.renderer.createElement(this._el_0,'li',this.debug(14,4,3));
    this._el_15 = this.renderer.createElement(this._el_14,'a',this.debug(15,4,7));
    this.renderer.setElementAttribute(this._el_15,'class','waves-effect waves-darkblue');
    this.renderer.setElementAttribute(this._el_15,'router-active','');
    this._RouterLinkWithHref_15_3 = new import12.RouterLinkWithHref(this.parentInjector.get(import13.Router),this.parentInjector.get(import14.ActivatedRoute),this.parentInjector.get(import15.LocationStrategy));
    this._text_16 = this.renderer.createText(this._el_15,'Grid (Nested)',this.debug(16,4,86));
    this._text_17 = this.renderer.createText(this._el_0,'\n   ',this.debug(17,4,108));
    this._el_18 = this.renderer.createElement(this._el_0,'li',this.debug(18,5,3));
    this._el_19 = this.renderer.createElement(this._el_18,'a',this.debug(19,5,7));
    this.renderer.setElementAttribute(this._el_19,'class','waves-effect waves-darkblue');
    this.renderer.setElementAttribute(this._el_19,'router-active','');
    this._RouterLinkWithHref_19_3 = new import12.RouterLinkWithHref(this.parentInjector.get(import13.Router),this.parentInjector.get(import14.ActivatedRoute),this.parentInjector.get(import15.LocationStrategy));
    this._text_20 = this.renderer.createText(this._el_19,'About',this.debug(20,5,86));
    this._text_21 = this.renderer.createText(this._el_0,'\n   ',this.debug(21,5,100));
    this._el_22 = this.renderer.createElement(this._el_0,'li',this.debug(22,6,3));
    this._el_23 = this.renderer.createElement(this._el_22,'a',this.debug(23,6,7));
    this.renderer.setElementAttribute(this._el_23,'class','waves-effect waves-darkblue');
    this.renderer.setElementAttribute(this._el_23,'router-active','');
    this._RouterLinkWithHref_23_3 = new import12.RouterLinkWithHref(this.parentInjector.get(import13.Router),this.parentInjector.get(import14.ActivatedRoute),this.parentInjector.get(import15.LocationStrategy));
    this._text_24 = this.renderer.createText(this._el_23,'Login',this.debug(24,6,86));
    this._text_25 = this.renderer.createText(this._el_0,'\n   ',this.debug(25,6,100));
    this._el_26 = this.renderer.createElement(this._el_0,'li',this.debug(26,7,3));
    this._el_27 = this.renderer.createElement(this._el_26,'a',this.debug(27,7,7));
    this.renderer.setElementAttribute(this._el_27,'class','waves-effect waves-darkblue');
    this.renderer.setElementAttribute(this._el_27,'router-active','');
    this._RouterLinkWithHref_27_3 = new import12.RouterLinkWithHref(this.parentInjector.get(import13.Router),this.parentInjector.get(import14.ActivatedRoute),this.parentInjector.get(import15.LocationStrategy));
    this._text_28 = this.renderer.createText(this._el_27,'Detail (Sub Module)',this.debug(28,7,87));
    this._text_29 = this.renderer.createText(this._el_0,'\n\n   ',this.debug(29,7,115));
    this._el_30 = this.renderer.createElement(this._el_0,'li',this.debug(30,9,3));
    this.renderer.setElementAttribute(this._el_30,'class','no-padding');
    this._text_31 = this.renderer.createText(this._el_30,'\n      ',this.debug(31,9,26));
    this._el_32 = this.renderer.createElement(this._el_30,'ul',this.debug(32,10,6));
    this.renderer.setElementAttribute(this._el_32,'class','collapsible');
    this.renderer.setElementAttribute(this._el_32,'data-collapsible','expandable');
    this._text_33 = this.renderer.createText(this._el_32,'\n         ',this.debug(33,10,60));
    this._el_34 = this.renderer.createElement(this._el_32,'li',this.debug(34,11,9));
    this._text_35 = this.renderer.createText(this._el_34,'\n            ',this.debug(35,11,13));
    this._el_36 = this.renderer.createElement(this._el_34,'a',this.debug(36,12,12));
    this.renderer.setElementAttribute(this._el_36,'class','collapsible-header');
    this._text_37 = this.renderer.createText(this._el_36,'Iframe Module',this.debug(37,12,78));
    this._el_38 = this.renderer.createElement(this._el_36,'i',this.debug(38,12,91));
    this.renderer.setElementAttribute(this._el_38,'class','mdi-navigation-arrow-drop-down');
    this._text_39 = this.renderer.createText(this._el_34,'\n            ',this.debug(39,12,141));
    this._el_40 = this.renderer.createElement(this._el_34,'div',this.debug(40,13,12));
    this.renderer.setElementAttribute(this._el_40,'class','collapsible-body');
    this._text_41 = this.renderer.createText(this._el_40,'\n               ',this.debug(41,13,42));
    this._el_42 = this.renderer.createElement(this._el_40,'ul',this.debug(42,14,15));
    this._text_43 = this.renderer.createText(this._el_42,'\n                  ',this.debug(43,14,19));
    this._el_44 = this.renderer.createElement(this._el_42,'li',this.debug(44,15,18));
    this._el_45 = this.renderer.createElement(this._el_44,'a',this.debug(45,15,22));
    this.renderer.setElementAttribute(this._el_45,'class','waves-effect waves-darkblue');
    this.renderer.setElementAttribute(this._el_45,'router-active','');
    this._RouterLinkWithHref_45_3 = new import12.RouterLinkWithHref(this.parentInjector.get(import13.Router),this.parentInjector.get(import14.ActivatedRoute),this.parentInjector.get(import15.LocationStrategy));
    this._text_46 = this.renderer.createText(this._el_45,'Bing Images',this.debug(46,15,111));
    this._text_47 = this.renderer.createText(this._el_42,'\n                  ',this.debug(47,15,131));
    this._el_48 = this.renderer.createElement(this._el_42,'li',this.debug(48,16,18));
    this._el_49 = this.renderer.createElement(this._el_48,'a',this.debug(49,16,22));
    this.renderer.setElementAttribute(this._el_49,'class','waves-effect waves-darkblue');
    this.renderer.setElementAttribute(this._el_49,'router-active','');
    this._RouterLinkWithHref_49_3 = new import12.RouterLinkWithHref(this.parentInjector.get(import13.Router),this.parentInjector.get(import14.ActivatedRoute),this.parentInjector.get(import15.LocationStrategy));
    this._text_50 = this.renderer.createText(this._el_49,'Bing Search',this.debug(50,16,111));
    this._text_51 = this.renderer.createText(this._el_42,'\n               ',this.debug(51,16,131));
    this._text_52 = this.renderer.createText(this._el_40,'\n            ',this.debug(52,17,20));
    this._text_53 = this.renderer.createText(this._el_34,'\n         ',this.debug(53,18,18));
    this._text_54 = this.renderer.createText(this._el_32,'\n      ',this.debug(54,19,14));
    this._text_55 = this.renderer.createText(this._el_30,'\n   ',this.debug(55,20,11));
    this._text_56 = this.renderer.createText(this._el_0,'\n',this.debug(56,21,8));
    this._text_57 = this.renderer.createText(parentRenderNode,'\n',this.debug(57,22,5));
    this._el_58 = this.renderer.createElement(parentRenderNode,'a',this.debug(58,23,0));
    this.renderer.setElementAttribute(this._el_58,'class','waves-effect waves-darkblue button-collapse');
    this.renderer.setElementAttribute(this._el_58,'data-activates','slide-out');
    this.renderer.setElementAttribute(this._el_58,'href','#');
    this._el_59 = this.renderer.createElement(this._el_58,'i',this.debug(59,23,91));
    this.renderer.setElementAttribute(this._el_59,'class','mdi-navigation-menu');
    this._text_60 = this.renderer.createText(parentRenderNode,'\n\n',this.debug(60,23,130));
    this._text_61 = this.renderer.createText(parentRenderNode,'\n',this.debug(61,25,23));
    this._text_62 = this.renderer.createText(parentRenderNode,'\n\n',this.debug(62,26,148));
    this._text_63 = this.renderer.createText(parentRenderNode,'\n',this.debug(63,28,74));
    this._text_64 = this.renderer.createText(parentRenderNode,'\n\n',this.debug(64,29,24));
    this._text_65 = this.renderer.createText(parentRenderNode,'\n',this.debug(65,31,23));
    this._text_66 = this.renderer.createText(parentRenderNode,'\n',this.debug(66,32,77));
    this._text_67 = this.renderer.createText(parentRenderNode,'\n\n',this.debug(67,33,24));
    this._text_68 = this.renderer.createText(parentRenderNode,'\n',this.debug(68,35,23));
    this._text_69 = this.renderer.createText(parentRenderNode,'\n',this.debug(69,36,79));
    this._text_70 = this.renderer.createText(parentRenderNode,'\n\n',this.debug(70,37,24));
    this._text_71 = this.renderer.createText(parentRenderNode,'\n',this.debug(71,39,23));
    this._text_72 = this.renderer.createText(parentRenderNode,'\n',this.debug(72,40,79));
    this._text_73 = this.renderer.createText(parentRenderNode,'\n\n',this.debug(73,41,24));
    var disposable_0:Function = this.renderer.listen(this._el_3,'click',this.eventHandler(this._handle_click_3_0.bind(this)));
    this._arr_0 = import5.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_1 = import8.UNINITIALIZED;
    this._expr_2 = import8.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_7,'click',this.eventHandler(this._handle_click_7_0.bind(this)));
    this._arr_1 = import5.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_4 = import8.UNINITIALIZED;
    this._expr_5 = import8.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_11,'click',this.eventHandler(this._handle_click_11_0.bind(this)));
    this._arr_2 = import5.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_7 = import8.UNINITIALIZED;
    this._expr_8 = import8.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_15,'click',this.eventHandler(this._handle_click_15_0.bind(this)));
    this._arr_3 = import5.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_10 = import8.UNINITIALIZED;
    this._expr_11 = import8.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_19,'click',this.eventHandler(this._handle_click_19_0.bind(this)));
    this._arr_4 = import5.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_13 = import8.UNINITIALIZED;
    this._expr_14 = import8.UNINITIALIZED;
    var disposable_5:Function = this.renderer.listen(this._el_23,'click',this.eventHandler(this._handle_click_23_0.bind(this)));
    this._arr_5 = import5.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_16 = import8.UNINITIALIZED;
    this._expr_17 = import8.UNINITIALIZED;
    var disposable_6:Function = this.renderer.listen(this._el_27,'click',this.eventHandler(this._handle_click_27_0.bind(this)));
    this._arr_6 = import5.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_19 = import8.UNINITIALIZED;
    this._expr_20 = import8.UNINITIALIZED;
    var disposable_7:Function = this.renderer.listen(this._el_45,'click',this.eventHandler(this._handle_click_45_0.bind(this)));
    this._arr_7 = import5.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_22 = import8.UNINITIALIZED;
    this._expr_23 = import8.UNINITIALIZED;
    var disposable_8:Function = this.renderer.listen(this._el_49,'click',this.eventHandler(this._handle_click_49_0.bind(this)));
    this._arr_8 = import5.pureProxy1((p0:any):any[] => {
      return [p0];
    });
    this._expr_25 = import8.UNINITIALIZED;
    this._expr_26 = import8.UNINITIALIZED;
    this.init([],[
      this._el_0,
      this._text_1,
      this._el_2,
      this._el_3,
      this._text_4,
      this._text_5,
      this._el_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._el_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._el_44,
      this._el_45,
      this._text_46,
      this._text_47,
      this._el_48,
      this._el_49,
      this._text_50,
      this._text_51,
      this._text_52,
      this._text_53,
      this._text_54,
      this._text_55,
      this._text_56,
      this._text_57,
      this._el_58,
      this._el_59,
      this._text_60,
      this._text_61,
      this._text_62,
      this._text_63,
      this._text_64,
      this._text_65,
      this._text_66,
      this._text_67,
      this._text_68,
      this._text_69,
      this._text_70,
      this._text_71,
      this._text_72,
      this._text_73
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8
    ]
    ,[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import12.RouterLinkWithHref) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._RouterLinkWithHref_3_3; }
    if (((token === import12.RouterLinkWithHref) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._RouterLinkWithHref_7_3; }
    if (((token === import12.RouterLinkWithHref) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 12)))) { return this._RouterLinkWithHref_11_3; }
    if (((token === import12.RouterLinkWithHref) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._RouterLinkWithHref_15_3; }
    if (((token === import12.RouterLinkWithHref) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._RouterLinkWithHref_19_3; }
    if (((token === import12.RouterLinkWithHref) && ((23 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._RouterLinkWithHref_23_3; }
    if (((token === import12.RouterLinkWithHref) && ((27 <= requestNodeIndex) && (requestNodeIndex <= 28)))) { return this._RouterLinkWithHref_27_3; }
    if (((token === import12.RouterLinkWithHref) && ((45 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._RouterLinkWithHref_45_3; }
    if (((token === import12.RouterLinkWithHref) && ((49 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._RouterLinkWithHref_49_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import8.SimpleChange} = (null as any);
    this.debug(3,1,7);
    changes = (null as any);
    this.debug(3,1,60);
    const currVal_1:any = this._arr_0('/');
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._RouterLinkWithHref_3_3.routerLink = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import8.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_3_3.ngOnChanges(changes); }
    this.debug(7,2,7);
    changes = (null as any);
    this.debug(7,2,60);
    const currVal_4:any = this._arr_1('/ticket');
    if (import5.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._RouterLinkWithHref_7_3.routerLink = currVal_4;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import8.SimpleChange(this._expr_4,currVal_4);
      this._expr_4 = currVal_4;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_7_3.ngOnChanges(changes); }
    this.debug(11,3,7);
    changes = (null as any);
    this.debug(11,3,60);
    const currVal_7:any = this._arr_2('/grid1');
    if (import5.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._RouterLinkWithHref_11_3.routerLink = currVal_7;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import8.SimpleChange(this._expr_7,currVal_7);
      this._expr_7 = currVal_7;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_11_3.ngOnChanges(changes); }
    this.debug(15,4,7);
    changes = (null as any);
    this.debug(15,4,60);
    const currVal_10:any = this._arr_3('/grid2');
    if (import5.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._RouterLinkWithHref_15_3.routerLink = currVal_10;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import8.SimpleChange(this._expr_10,currVal_10);
      this._expr_10 = currVal_10;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_15_3.ngOnChanges(changes); }
    this.debug(19,5,7);
    changes = (null as any);
    this.debug(19,5,60);
    const currVal_13:any = this._arr_4('/about');
    if (import5.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._RouterLinkWithHref_19_3.routerLink = currVal_13;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import8.SimpleChange(this._expr_13,currVal_13);
      this._expr_13 = currVal_13;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_19_3.ngOnChanges(changes); }
    this.debug(23,6,7);
    changes = (null as any);
    this.debug(23,6,60);
    const currVal_16:any = this._arr_5('/login');
    if (import5.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this._RouterLinkWithHref_23_3.routerLink = currVal_16;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import8.SimpleChange(this._expr_16,currVal_16);
      this._expr_16 = currVal_16;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_23_3.ngOnChanges(changes); }
    this.debug(27,7,7);
    changes = (null as any);
    this.debug(27,7,60);
    const currVal_19:any = this._arr_6('/detail');
    if (import5.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this._RouterLinkWithHref_27_3.routerLink = currVal_19;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import8.SimpleChange(this._expr_19,currVal_19);
      this._expr_19 = currVal_19;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_27_3.ngOnChanges(changes); }
    this.debug(45,15,22);
    changes = (null as any);
    this.debug(45,15,75);
    const currVal_22:any = this._arr_7('/iframe/webpage1');
    if (import5.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this._RouterLinkWithHref_45_3.routerLink = currVal_22;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import8.SimpleChange(this._expr_22,currVal_22);
      this._expr_22 = currVal_22;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_45_3.ngOnChanges(changes); }
    this.debug(49,16,22);
    changes = (null as any);
    this.debug(49,16,75);
    const currVal_25:any = this._arr_8('/iframe/webpage2');
    if (import5.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this._RouterLinkWithHref_49_3.routerLink = currVal_25;
      if ((changes === (null as any))) { (changes = {}); }
      changes['routerLink'] = new import8.SimpleChange(this._expr_25,currVal_25);
      this._expr_25 = currVal_25;
    }
    if ((changes !== (null as any))) { this._RouterLinkWithHref_49_3.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    this.debug(3,1,7);
    const currVal_2:any = this._RouterLinkWithHref_3_3.href;
    if (import5.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementProperty(this._el_3,'href',this.viewUtils.sanitizer.sanitize(import16.SecurityContext.URL,currVal_2));
      this._expr_2 = currVal_2;
    }
    this.debug(7,2,7);
    const currVal_5:any = this._RouterLinkWithHref_7_3.href;
    if (import5.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementProperty(this._el_7,'href',this.viewUtils.sanitizer.sanitize(import16.SecurityContext.URL,currVal_5));
      this._expr_5 = currVal_5;
    }
    this.debug(11,3,7);
    const currVal_8:any = this._RouterLinkWithHref_11_3.href;
    if (import5.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementProperty(this._el_11,'href',this.viewUtils.sanitizer.sanitize(import16.SecurityContext.URL,currVal_8));
      this._expr_8 = currVal_8;
    }
    this.debug(15,4,7);
    const currVal_11:any = this._RouterLinkWithHref_15_3.href;
    if (import5.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementProperty(this._el_15,'href',this.viewUtils.sanitizer.sanitize(import16.SecurityContext.URL,currVal_11));
      this._expr_11 = currVal_11;
    }
    this.debug(19,5,7);
    const currVal_14:any = this._RouterLinkWithHref_19_3.href;
    if (import5.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementProperty(this._el_19,'href',this.viewUtils.sanitizer.sanitize(import16.SecurityContext.URL,currVal_14));
      this._expr_14 = currVal_14;
    }
    this.debug(23,6,7);
    const currVal_17:any = this._RouterLinkWithHref_23_3.href;
    if (import5.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementProperty(this._el_23,'href',this.viewUtils.sanitizer.sanitize(import16.SecurityContext.URL,currVal_17));
      this._expr_17 = currVal_17;
    }
    this.debug(27,7,7);
    const currVal_20:any = this._RouterLinkWithHref_27_3.href;
    if (import5.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementProperty(this._el_27,'href',this.viewUtils.sanitizer.sanitize(import16.SecurityContext.URL,currVal_20));
      this._expr_20 = currVal_20;
    }
    this.debug(45,15,22);
    const currVal_23:any = this._RouterLinkWithHref_45_3.href;
    if (import5.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementProperty(this._el_45,'href',this.viewUtils.sanitizer.sanitize(import16.SecurityContext.URL,currVal_23));
      this._expr_23 = currVal_23;
    }
    this.debug(49,16,22);
    const currVal_26:any = this._RouterLinkWithHref_49_3.href;
    if (import5.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementProperty(this._el_49,'href',this.viewUtils.sanitizer.sanitize(import16.SecurityContext.URL,currVal_26));
      this._expr_26 = currVal_26;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this.debug(3,1,7);
    this._RouterLinkWithHref_3_3.ngOnDestroy();
    this.debug(7,2,7);
    this._RouterLinkWithHref_7_3.ngOnDestroy();
    this.debug(11,3,7);
    this._RouterLinkWithHref_11_3.ngOnDestroy();
    this.debug(15,4,7);
    this._RouterLinkWithHref_15_3.ngOnDestroy();
    this.debug(19,5,7);
    this._RouterLinkWithHref_19_3.ngOnDestroy();
    this.debug(23,6,7);
    this._RouterLinkWithHref_23_3.ngOnDestroy();
    this.debug(27,7,7);
    this._RouterLinkWithHref_27_3.ngOnDestroy();
    this.debug(45,15,22);
    this._RouterLinkWithHref_45_3.ngOnDestroy();
    this.debug(49,16,22);
    this._RouterLinkWithHref_49_3.ngOnDestroy();
  }
  private _handle_click_3_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(3,1,7);
    const pd_0:any = ((<any>this._RouterLinkWithHref_3_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_7_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(7,2,7);
    const pd_0:any = ((<any>this._RouterLinkWithHref_7_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_11_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(11,3,7);
    const pd_0:any = ((<any>this._RouterLinkWithHref_11_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_15_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(15,4,7);
    const pd_0:any = ((<any>this._RouterLinkWithHref_15_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_19_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(19,5,7);
    const pd_0:any = ((<any>this._RouterLinkWithHref_19_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_23_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(23,6,7);
    const pd_0:any = ((<any>this._RouterLinkWithHref_23_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_27_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(27,7,7);
    const pd_0:any = ((<any>this._RouterLinkWithHref_27_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_45_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(45,15,22);
    const pd_0:any = ((<any>this._RouterLinkWithHref_45_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
  private _handle_click_49_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.debug(49,16,22);
    const pd_0:any = ((<any>this._RouterLinkWithHref_49_3.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_NavSidebarComponent0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import4.AppElement):import3.AppView<import1.NavSidebarComponent> {
  if ((renderType_NavSidebarComponent === (null as any))) { (renderType_NavSidebarComponent = viewUtils.createRenderComponentType('C:/Development/angular2-webpack2-dotnet-starter/src/app-components/nav/sidebar/nav-sidebar.template.html',0,import10.ViewEncapsulation.None,styles_NavSidebarComponent,{})); }
  return new _View_NavSidebarComponent0(viewUtils,parentInjector,declarationEl);
}